### ISSUE TITLE
get_android_resources function exception struct.error: unpack requires a buffer of 2 bytes

### ISSUE THREAD

**Issue by ohyeah521** [androguard/androguard#1017]
`rsrc = apk.get_android_resources()`

```
Traceback (most recent call last):
  File "D:\\venv\Lib\site-packages\androguard\core\apk\__init__.py", line 1543, in get_android_resources
    return self.arsc["resources.arsc"]
           ~~~~~~~~~^^^^^^^^^^^^^^^^^^
KeyError: 'resources.arsc'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\\mobsf\StaticAnalyzer\views\android\strings.py", line 76, in strings_from_apk
    rsrc = apk.get_android_resources()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\\venv\Lib\site-packages\androguard\core\apk\__init__.py", line 1549, in get_android_resources
    self.arsc["resources.arsc"] = ARSCParser(self.zip.read("resources.arsc"))
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\\venv\Lib\site-packages\androguard\core\axml\__init__.py", line 1491, in __init__
    ate = ARSCResTableEntry(self.buff, res_id, pc)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\\venv\Lib\site-packages\androguard\core\axml\__init__.py", line 2868, in __init__
    self.item = ARSCComplex(buff, parent)
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\\venv\Lib\site-packages\androguard\core\axml\__init__.py", line 2926, in __init__
    self.items.append((unpack('<I', buff.read(4))[0], ARSCResStringPoolRef(buff, self.parent)))
                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\\venv\Lib\site-packages\androguard\core\axml\__init__.py", line 2943, in __init__
    self.size, = unpack("<H", buff.read(2))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
struct.error: unpack requires a buffer of 2 bytes
```

**Comment by erev0s** [comment]
hi @ohyeah521 , cant replicate this with the example apks.
could you please share the apk?

**Comment by ohyeah521** [comment]
@erev0s  https://drive.google.com/file/d/1yy5NXuB5bo7uEoE8LRIAYvUAFaeEOf6d/view?usp=drive_link

**Comment by erev0s** [comment]
@ohyeah521 cant access this. Feel free to use a service like https://tria.ge

**Comment by ohyeah521** [comment]
@erev0s  https://tria.ge/submit/240318-ppdctahc9z

**Comment by erev0s** [comment]
@ohyeah521 please use an install with the latest commits and try again as I cant replicate the issue
~~~~
pip install git+https://github.com/androguard/androguard
~~~~

**Comment by erev0s** [comment]
This should be resolved now. Thank you for your help @ohyeah521

**Comment by h3isenbug** [comment]
I have the same problem with androguard version 4.1.3.
I'm calling this method:
```resources = apk.get_android_resources()```
apk: https://drive.google.com/file/d/1_yHPa0IZ3oyS_r-02E2OkP-CiDeusn7a/view?usp=sharing

thanks in advance
@erev0s
