### ISSUE TITLE
Installation on ARM64

### ISSUE THREAD

**Issue by QU35T-code** [androguard/androguard#1027]
Hi,

There is a problem since the last update of androguard on **ARM64**. The project no longer builds and there's an error with the **PyQt5** dependency.

### Describe what actually happened

```bash
pipx install androguard
```

```bash
2024-02-27T18:50:21.6749880Z 2758.0 installing androguard...
2024-02-27T18:50:21.6750390Z 3244.1 Fatal error from pip prevented installation. Full pip output in file:
2024-02-27T18:50:21.6751050Z 3244.1     /root/.local/state/pipx/log/cmd_2024-02-27_18.32.14_pip_errors.log
2024-02-27T18:50:21.6751400Z 3244.1 
2024-02-27T18:50:21.6753770Z 3244.1 pip seemed to fail to build package:
2024-02-27T18:50:21.6754100Z 3244.1     PyQt5
2024-02-27T18:50:21.6754300Z 3244.2 Error installing androguard.
```

### System Information

- Androguard Version: master
- Python Version: 3.11.7
- ARM64

**Comment by ehrenb** [comment]
Related to https://github.com/androguard/androguard/issues/1018

**Comment by QU35T-code** [comment]
Hi @ehrenb 

This doesn't work with **pipx**.
I'll try it with poetry but I think I'll get the same result.

**pipx :**

```bash
pipx install git+https://github.com/ehrenb/androguard@pyqt5-qt5-fix --force
```

```bash
[...]
pipx >(run_subprocess:168): running <checking pip's availability>
pipx >(run_subprocess:190): stdout: ModuleSpec(name='pip', loader=<_frozen_importlib_external.SourceFileLoader object at 0xffff9cdfaf10>, origin='/root/.local/share/pipx/shared/lib/python3.11/site-packages/pip/__init__.py', submodule_search_locations=['/root/.local/share/pipx/shared/lib/python3.11/site-packages/pip'])
pipx >(run_subprocess:193): returncode: 0
Installing to existing venv 'androguard'
creating virtual environment...
pipx >(run_subprocess:168): running /root/.pyenv/versions/3.11.8/bin/python3.11 -m venv --without-pip /root/.local/share/pipx/venvs/androguard
pipx >(run_subprocess:190): stdout:
pipx >(run_subprocess:192): stderr:
pipx >(run_subprocess:193): returncode: 0
pipx >(run_subprocess:168): running <checking pip's availability>
pipx >(run_subprocess:190): stdout: ModuleSpec(name='pip', loader=<_frozen_importlib_external.SourceFileLoader object at 0xffff8d95af10>, origin='/root/.local/share/pipx/shared/lib/python3.11/site-packages/pip/__init__.py', submodule_search_locations=['/root/.local/share/pipx/shared/lib/python3.11/site-packages/pip'])
pipx >(run_subprocess:193): returncode: 0
pipx >(run_subprocess:168): running /root/.local/share/pipx/venvs/androguard/bin/python -c import sysconfig; print(sysconfig.get_path('purelib'))
pipx >(run_subprocess:190): stdout: /root/.local/share/pipx/venvs/androguard/lib/python3.11/site-packages
pipx >(run_subprocess:193): returncode: 0
pipx >(run_subprocess:168): running /root/.local/share/pipx/venvs/androguard/bin/python --version
pipx >(run_subprocess:190): stdout: Python 3.11.8
pipx >(run_subprocess:192): stderr:
pipx >(run_subprocess:193): returncode: 0
pipx >(_parsed_package_to_package_or_url:137): cleaned package spec: /tmp/androguard
installing androguard from spec '/tmp/androguard'...
pipx >(run_subprocess:168): running /root/.local/share/pipx/venvs/androguard/bin/python -m pip --no-input install --force-reinstall /tmp/androguard
pipx >(run_subprocess:193): returncode: -9
pipx >(subprocess_post_check_handle_pip_error:327): '/root/.local/share/pipx/venvs/androguard/bin/python -m pip --no-input install --force-reinstall /tmp/androguard' failed
pipx >(subprocess_post_check_handle_pip_error:342): Fatal error from pip prevented installation. Full pip output in file:
    /root/.local/state/pipx/log/cmd_2024-04-03_07.50.23_pip_errors.log

pipx >(analyze_pip_output:306): pip seemed to fail to build package:
    PyQt5

pipx >(remove_venv:187): ⚠️  Not removing existing venv /root/.local/share/pipx/venvs/androguard because it was not created in this session
Error installing androguard from spec '/tmp/androguard'.
pipx >(cli:924): PipxError: Error installing androguard from spec '/tmp/androguard'.
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.11.8/lib/python3.11/site-packages/pipx/main.py", line 921, in cli
    return run_pipx_command(parsed_pipx_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.pyenv/versions/3.11.8/lib/python3.11/site-packages/pipx/main.py", line 219, in run_pipx_command
    return commands.install(
           ^^^^^^^^^^^^^^^^^
  File "/root/.pyenv/versions/3.11.8/lib/python3.11/site-packages/pipx/commands/install.py", line 91, in install
    venv.install_package(
  File "/root/.pyenv/versions/3.11.8/lib/python3.11/site-packages/pipx/venv.py", line 254, in install_package
    raise PipxError(f"Error installing {full_package_description(package_name, package_or_url)}.")
pipx.util.PipxError: Error installing androguard from spec '/tmp/androguard'.
pipx >(cli:932): pipx finished.
```

**Comment by ehrenb** [comment]
> Hi @ehrenb
> 
> This doesn't work with **pipx**. I'll try it with poetry but I think I'll get the same result.
> 
> **pipx :**
> 
> ```shell
> pipx install git+https://github.com/ehrenb/androguard@pyqt5-qt5-fix --force
> ```
> 
> ```shell
> [...]
> pipx >(run_subprocess:168): running <checking pip's availability>
> pipx >(run_subprocess:190): stdout: ModuleSpec(name='pip', loader=<_frozen_importlib_external.SourceFileLoader object at 0xffff9cdfaf10>, origin='/root/.local/share/pipx/shared/lib/python3.11/site-packages/pip/__init__.py', submodule_search_locations=['/root/.local/share/pipx/shared/lib/python3.11/site-packages/pip'])
> pipx >(run_subprocess:193): returncode: 0
> Installing to existing venv 'androguard'
> creating virtual environment...
> pipx >(run_subprocess:168): running /root/.pyenv/versions/3.11.8/bin/python3.11 -m venv --without-pip /root/.local/share/pipx/venvs/androguard
> pipx >(run_subprocess:190): stdout:
> pipx >(run_subprocess:192): stderr:
> pipx >(run_subprocess:193): returncode: 0
> pipx >(run_subprocess:168): running <checking pip's availability>
> pipx >(run_subprocess:190): stdout: ModuleSpec(name='pip', loader=<_frozen_importlib_external.SourceFileLoader object at 0xffff8d95af10>, origin='/root/.local/share/pipx/shared/lib/python3.11/site-packages/pip/__init__.py', submodule_search_locations=['/root/.local/share/pipx/shared/lib/python3.11/site-packages/pip'])
> pipx >(run_subprocess:193): returncode: 0
> pipx >(run_subprocess:168): running /root/.local/share/pipx/venvs/androguard/bin/python -c import sysconfig; print(sysconfig.get_path('purelib'))
> pipx >(run_subprocess:190): stdout: /root/.local/share/pipx/venvs/androguard/lib/python3.11/site-packages
> pipx >(run_subprocess:193): returncode: 0
> pipx >(run_subprocess:168): running /root/.local/share/pipx/venvs/androguard/bin/python --version
> pipx >(run_subprocess:190): stdout: Python 3.11.8
> pipx >(run_subprocess:192): stderr:
> pipx >(run_subprocess:193): returncode: 0
> pipx >(_parsed_package_to_package_or_url:137): cleaned package spec: /tmp/androguard
> installing androguard from spec '/tmp/androguard'...
> pipx >(run_subprocess:168): running /root/.local/share/pipx/venvs/androguard/bin/python -m pip --no-input install --force-reinstall /tmp/androguard
> pipx >(run_subprocess:193): returncode: -9
> pipx >(subprocess_post_check_handle_pip_error:327): '/root/.local/share/pipx/venvs/androguard/bin/python -m pip --no-input install --force-reinstall /tmp/androguard' failed
> pipx >(subprocess_post_check_handle_pip_error:342): Fatal error from pip prevented installation. Full pip output in file:
>     /root/.local/state/pipx/log/cmd_2024-04-03_07.50.23_pip_errors.log
> 
> pipx >(analyze_pip_output:306): pip seemed to fail to build package:
>     PyQt5
> 
> pipx >(remove_venv:187): ⚠️  Not removing existing venv /root/.local/share/pipx/venvs/androguard because it was not created in this session
> Error installing androguard from spec '/tmp/androguard'.
> pipx >(cli:924): PipxError: Error installing androguard from spec '/tmp/androguard'.
> Traceback (most recent call last):
>   File "/root/.pyenv/versions/3.11.8/lib/python3.11/site-packages/pipx/main.py", line 921, in cli
>     return run_pipx_command(parsed_pipx_args)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/root/.pyenv/versions/3.11.8/lib/python3.11/site-packages/pipx/main.py", line 219, in run_pipx_command
>     return commands.install(
>            ^^^^^^^^^^^^^^^^^
>   File "/root/.pyenv/versions/3.11.8/lib/python3.11/site-packages/pipx/commands/install.py", line 91, in install
>     venv.install_package(
>   File "/root/.pyenv/versions/3.11.8/lib/python3.11/site-packages/pipx/venv.py", line 254, in install_package
>     raise PipxError(f"Error installing {full_package_description(package_name, package_or_url)}.")
> pipx.util.PipxError: Error installing androguard from spec '/tmp/androguard'.
> pipx >(cli:932): pipx finished.
> ```
> 
> **Log file :**
> 
> ```shell
> PIP STDOUT
> ----------
> Processing /tmp/androguard
>   Installing build dependencies: started
>   Installing build dependencies: finished with status 'done'
>   Getting requirements to build wheel: started
>   Getting requirements to build wheel: finished with status 'done'
>   Preparing metadata (pyproject.toml): started
>   Preparing metadata (pyproject.toml): finished with status 'done'
> Collecting PyQt5 (from androguard==4.1.1)
>   Using cached PyQt5-5.15.10.tar.gz (3.2 MB)
>   Installing build dependencies: started
>   Installing build dependencies: finished with status 'done'
>   Getting requirements to build wheel: started
>   Getting requirements to build wheel: finished with status 'done'
>   Preparing metadata (pyproject.toml): started
> 
> PIP STDERR
> ----------
> ```

It looks like androguard was already installed when you ran. Could you `pipx uninstall androguard` and try again?  I was able to install using pipx and poetry on Linux X64.

**Comment by ehrenb** [comment]
@erev0s maybe we can add MacOS Silicon runners for testing in future? https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source/

**Comment by erev0s** [comment]
@ehrenb great idea, I will look into it hopefully somewhere within this week.
