### ISSUE TITLE
Facebook app (Android 14 - version) - unpack requires a buffer of 4 bytes

### ISSUE THREAD

**Issue by leosol** [androguard/androguard#1043]
APK to download:
https://drive.google.com/file/d/1UJXLgjVvr9W9wiR0pvb8iXwpXzVHDoo9/view?usp=sharing

(...)
2024-04-27 18:32:27.629 | WARNING  | androguard.core.axml:__init__:2947 - res0 must be always zero!
2024-04-27 18:32:27.629 | WARNING  | androguard.core.axml:__init__:2947 - res0 must be always zero!
2024-04-27 18:32:27.629 | WARNING  | androguard.core.axml:__init__:2947 - res0 must be always zero!
2024-04-27 18:32:27.630 | ERROR    | androguard.core.axml:__init__:2952 - unpack requires a buffer of 4 bytes
Traceback (most recent call last):
  File "I:\git\forensicmate-static-analysis\venv\lib\site-packages\androguard\core\apk\__init__.py", line 1543, in get_android_resources
    return self.arsc["resources.arsc"]
KeyError: 'resources.arsc'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "I:\git\forensicmate-static-analysis\pymate\device_link\app_bag.py", line 35, in __init__
    app = App(apk_base_path=base, extra_split_pkgs=splited_items)
  File "I:\git\forensicmate-static-analysis\pymate\device_link\app.py", line 19, in __init__
    self.app_name = self.apk.get_app_name()
  File "I:\git\forensicmate-static-analysis\venv\lib\site-packages\androguard\core\apk\__init__.py", line 481, in get_app_name
    res_parser = self.get_android_resources()
  File "I:\git\forensicmate-static-analysis\venv\lib\site-packages\androguard\core\apk\__init__.py", line 1549, in get_android_resources
    self.arsc["resources.arsc"] = ARSCParser(self.zip.read("resources.arsc"))
  File "I:\git\forensicmate-static-analysis\venv\lib\site-packages\androguard\core\axml\__init__.py", line 1491, in __init__
    ate = ARSCResTableEntry(self.buff, res_id, pc)
  File "I:\git\forensicmate-static-analysis\venv\lib\site-packages\androguard\core\axml\__init__.py", line 2868, in __init__
    self.item = ARSCComplex(buff, parent)
  File "I:\git\forensicmate-static-analysis\venv\lib\site-packages\androguard\core\axml\__init__.py", line 2926, in __init__
    self.items.append((unpack('<I', buff.read(4))[0], ARSCResStringPoolRef(buff, self.parent)))
struct.error: unpack requires a buffer of 4 bytes
Traceback (most recent call last):
  File "I:\git\forensicmate-static-analysis\venv\lib\site-packages\androguard\core\apk\__init__.py", line 1543, in get_android_resources
    return self.arsc["resources.arsc"]
KeyError: 'resources.arsc'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "I:\git\forensicmate-static-analysis\pymate\device_link\app_bag.py", line 35, in __init__
    app = App(apk_base_path=base, extra_split_pkgs=splited_items)
  File "I:\git\forensicmate-static-analysis\pymate\device_link\app.py", line 19, in __init__
    self.app_name = self.apk.get_app_name()
  File "I:\git\forensicmate-static-analysis\venv\lib\site-packages\androguard\core\apk\__init__.py", line 481, in get_app_name
    res_parser = self.get_android_resources()
  File "I:\git\forensicmate-static-analysis\venv\lib\site-packages\androguard\core\apk\__init__.py", line 1549, in get_android_resources
    self.arsc["resources.arsc"] = ARSCParser(self.zip.read("resources.arsc"))
  File "I:\git\forensicmate-static-analysis\venv\lib\site-packages\androguard\core\axml\__init__.py", line 1491, in __init__
    ate = ARSCResTableEntry(self.buff, res_id, pc)
  File "I:\git\forensicmate-static-analysis\venv\lib\site-packages\androguard\core\axml\__init__.py", line 2868, in __init__
    self.item = ARSCComplex(buff, parent)
  File "I:\git\forensicmate-static-analysis\venv\lib\site-packages\androguard\core\axml\__init__.py", line 2926, in __init__
    self.items.append((unpack('<I', buff.read(4))[0], ARSCResStringPoolRef(buff, self.parent)))
struct.error: unpack requires a buffer of 4 bytes

**Comment by erev0s** [comment]
@leosol there is a reason there is a template when opening a new issue.
Please use the latest version
