### ISSUE TITLE
Error detecting the version of libcrypto

### ISSUE THREAD

**Issue by QU35T-code** [androguard/androguard#1060]
### Describe what you wanted to do

Install androguard.

### Describe what actually happened

```bash
pipx install --system-site-packages androguard
  installed package androguard 4.1.2, installed using Python 3.11.9
  These apps are now globally available
    - androguard
done! ✨ 🌟 ✨
```

```bash
androguard --help
Traceback (most recent call last):
  File "/root/.local/bin/androguard", line 5, in <module>
    from androguard.cli.cli import entry_point
  File "/root/.local/share/pipx/venvs/androguard/lib/python3.11/site-packages/androguard/cli/cli.py", line 13, in <module>
    from androguard.cli.main import (androarsc_main,
  File "/root/.local/share/pipx/venvs/androguard/lib/python3.11/site-packages/androguard/cli/main.py", line 14, in <module>
    from oscrypto import asymmetric
  File "/root/.local/share/pipx/venvs/androguard/lib/python3.11/site-packages/oscrypto/asymmetric.py", line 19, in <module>
    from ._asymmetric import _unwrap_private_key_info
  File "/root/.local/share/pipx/venvs/androguard/lib/python3.11/site-packages/oscrypto/_asymmetric.py", line 27, in <module>
    from .kdf import pbkdf1, pbkdf2, pkcs12_kdf
  File "/root/.local/share/pipx/venvs/androguard/lib/python3.11/site-packages/oscrypto/kdf.py", line 9, in <module>
    from .util import rand_bytes
  File "/root/.local/share/pipx/venvs/androguard/lib/python3.11/site-packages/oscrypto/util.py", line 14, in <module>
    from ._openssl.util import rand_bytes
  File "/root/.local/share/pipx/venvs/androguard/lib/python3.11/site-packages/oscrypto/_openssl/util.py", line 6, in <module>
    from ._libcrypto import libcrypto, libcrypto_version_info, handle_openssl_error
  File "/root/.local/share/pipx/venvs/androguard/lib/python3.11/site-packages/oscrypto/_openssl/_libcrypto.py", line 9, in <module>
    from ._libcrypto_cffi import (
  File "/root/.local/share/pipx/venvs/androguard/lib/python3.11/site-packages/oscrypto/_openssl/_libcrypto_cffi.py", line 44, in <module>
    raise LibraryNotFoundError('Error detecting the version of libcrypto')
oscrypto.errors.LibraryNotFoundError: Error detecting the version of libcrypto
```

### System Information

- Androguard Version: master
- Python Version: 3.11.9
- ARM (mac) + AMD

_Catched by the Exegol pipeline_

**Comment by erev0s** [comment]
Hi @QU35T-code , given that we had some issues lately with ARM and MACs I have added a test build to run on ARM64 on Macos-14.
The [test](https://github.com/androguard/androguard/actions/runs/9372505178/job/25804117407#step:1:8) was successful. I cant really replicate this.

**Comment by QU35T-code** [comment]
Seems to be related to this issue : https://github.com/wbond/oscrypto/issues/78

**Comment by QU35T-code** [comment]
> Hi @QU35T-code , given that we had some issues lately with ARM and MACs I have added a test build to run on ARM64 on Macos-14. The [test](https://github.com/androguard/androguard/actions/runs/9372505178/job/25804117407#step:1:8) was successful. I cant really replicate this.

This bug isn't only with ARM !

https://github.com/ThePorgs/Exegol-images/actions/runs/9372907132/job/25813095292

<img width="1149" alt="image" src="https://github.com/androguard/androguard/assets/51704860/280e1274-f6af-4491-91ec-ed0b79c97cfe">

**Comment by QU35T-code** [comment]
Can be this commit ! https://github.com/androguard/androguard/commit/be77adf9c8bbeb0349548c0f306547114551b888

**Comment by erev0s** [comment]
@QU35T-code it seems to be a bug in oscrypto where the regex would fail to recognize the right version of SSL due to insufficient check on multiple digits. It seems that this [has been fixed](https://github.com/wbond/oscrypto/commit/d5f3437ed24257895ae1edd9e503cfb352e635a8) a long time now, but there is no release.
A quick fix would be to pin to the latest commit
~~~~
oscrypto = "{ git = "https://github.com/wbond/oscrypto.git", rev = "1547f53" }"
~~~~
Maybe we could consider switching to an alternative library as well, as currently there are only 2 places where it is used.

**Comment by QU35T-code** [comment]
Hey @erev0s,

Thanks for your help, I managed to fix the problem that way.

```bash
> pipx install git+https://github.com/androguard/androguard
  installed package androguard 4.1.2, installed using Python 3.11.9
  These apps are now globally available
    - androguard
done! ✨ 🌟 ✨

> androguard --version
Traceback (most recent call last):
oscrypto.errors.LibraryNotFoundError: Error detecting the version of libcrypto
```

```bash
> rm -rf /root/.local/share/pipx/venvs/androguard/lib/python3.11/site-packages/oscrypto*

> pipx inject androguard git+https://github.com/wbond/oscrypto.git@master
  injected package oscrypto into venv androguard
  done! ✨ 🌟 ✨

> androguard --version
androguard, version 4.1.2
```

**Comment by QU35T-code** [comment]
Is it not possible for you to modify the requirements to use the latest version of oscrypto -> `master` (which is not on pypi) ?

**Comment by erev0s** [comment]
> Is it not possible for you to modify the requirements to use the latest version of oscrypto -> `master` or another latest commit (which is not on pypi) ?

hi @erev0s , yes that would be possible but I am not sure if it is the best action here. I am considering alternatives that will also fix the issue.

**Comment by ehrenb** [comment]
I too just encountered this issue.  On Ubuntu 24.04 x86-64 Python3.12 OpenSSL Version 3.0.13.  I'll apply the patch above to get unblocked.  May be a good idea to move away from this dependency, since that patch hasn't been pushed to a release, and the most recent release was in 2022.  Additionally, I don't see official support beyond Python 3.11 or Ubuntu 24.04 listed.

**Comment by erev0s** [comment]
https://github.com/androguard/androguard/pull/1076

**Comment by BreakfastSerial** [comment]
I've just installed the latest version of androguard via pip3 and am facing the same issue.

```
(androguard-venv) user@debmobi:~$ androguard 
Traceback (most recent call last):
  File "/home/user/androguard-venv/bin/androguard", line 5, in <module>
    from androguard.cli.cli import entry_point
  File "/home/user/androguard-venv/lib/python3.11/site-packages/androguard/cli/cli.py", line 13, in <module>
    from androguard.cli.main import (androarsc_main,
  File "/home/user/androguard-venv/lib/python3.11/site-packages/androguard/cli/main.py", line 14, in <module>
    from oscrypto import asymmetric
  File "/home/user/androguard-venv/lib/python3.11/site-packages/oscrypto/asymmetric.py", line 19, in <module>
    from ._asymmetric import _unwrap_private_key_info
  File "/home/user/androguard-venv/lib/python3.11/site-packages/oscrypto/_asymmetric.py", line 27, in <module>
    from .kdf import pbkdf1, pbkdf2, pkcs12_kdf
  File "/home/user/androguard-venv/lib/python3.11/site-packages/oscrypto/kdf.py", line 9, in <module>
    from .util import rand_bytes
  File "/home/user/androguard-venv/lib/python3.11/site-packages/oscrypto/util.py", line 14, in <module>
    from ._openssl.util import rand_bytes
  File "/home/user/androguard-venv/lib/python3.11/site-packages/oscrypto/_openssl/util.py", line 6, in <module>
    from ._libcrypto import libcrypto, libcrypto_version_info, handle_openssl_error
  File "/home/user/androguard-venv/lib/python3.11/site-packages/oscrypto/_openssl/_libcrypto.py", line 15, in <module>
    from ._libcrypto_ctypes import (
  File "/home/user/androguard-venv/lib/python3.11/site-packages/oscrypto/_openssl/_libcrypto_ctypes.py", line 47, in <module>
    raise LibraryNotFoundError('Error detecting the version of libcrypto')
oscrypto.errors.LibraryNotFoundError: Error detecting the version of libcrypto
```
