### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable when calling `get_source`

### ISSUE THREAD

**Issue by aitviid** [androguard/androguard#1079]
### Describe what you wanted to do

Print source code of this APK: https://updates.signal.org/android/Signal-Android-website-prod-universal-release-7.17.5.apk

The issue occurs for other files as well.

### Describe what you expected

The snippet below should print the source code of the selected two methods without issues:

```python
from loguru import logger
from core.apk import APK
from core.dex import DEX
from decompiler.decompiler import DecompilerDAD
from core.analysis.analysis import Analysis

logger.disable("")

apk = APK("Signal-Android-website-prod-universal-release-7.17.5.apk")

analysis = Analysis()
for dex_bytes in apk.get_all_dex():
    df = DEX(dex_bytes, using_api=apk.get_target_sdk_version())
    analysis.add(df)
    df.set_decompiler(DecompilerDAD(df, analysis))

analysis.create_xref()

example_methods = (
    ("Landroidx/appcompat/app/LayoutIncludeDetector;", "isParserOutdated"),
    ("Landroid/support/v4/os/ResultReceiver;", "send")
)


for method in analysis.get_methods():
    encoded_method = method.get_method()

    if (encoded_method.class_name, encoded_method.name) not in example_methods:
        continue

    print(f"{encoded_method.name = }")
    print(f"{encoded_method.class_name = }")
    print(encoded_method.get_source())
```

### Describe what actually happened

The code crashed with `TypeError: 'NoneType' object is not subscriptable` because the 
`decompiler.util.get_type` function got called from within 
`decompiler.basic_blocks.CatchBlock.visit_exception` with `atype` set to `None`:

```
Traceback (most recent call last):
  File "script.py", line 37, in <module>
    encoded_method.get_source()
  File "androguard/androguard/core/dex/__init__.py", line 3236, in get_source
    return self.CM.decompiler_ob.get_source_method(self)
  File "androguard/androguard/decompiler/decompiler.py", line 57, in get_source_method
    z.process()
  File "androguard/androguard/decompiler/decompile.py", line 197, in process
    self.writer.write_method()
  File "androguard/androguard/decompiler/writer.py", line 192, in write_method
    self.visit_node(self.graph.entry)
  File "androguard/androguard/decompiler/writer.py", line 208, in visit_node
    node.visit(self)
  File "androguard/androguard/decompiler/basic_blocks.py", line 158, in visit
    return visitor.visit_cond_node(self)
  File "androguard/androguard/decompiler/writer.py", line 316, in visit_cond_node
    self.visit_node(cond.true)
  File "androguard/androguard/decompiler/writer.py", line 208, in visit_node
    node.visit(self)
  File "androguard/androguard/decompiler/basic_blocks.py", line 72, in visit
    return visitor.visit_statement_node(self)
  File "androguard/androguard/decompiler/writer.py", line 387, in visit_statement_node
    self.visit_node(sucs[0])
  File "androguard/androguard/decompiler/writer.py", line 208, in visit_node
    node.visit(self)
  File "androguard/androguard/decompiler/basic_blocks.py", line 281, in visit
    visitor.visit_try_node(self)
  File "androguard/androguard/decompiler/writer.py", line 397, in visit_try_node
    self.visit_node(catch)
  File "androguard/androguard/decompiler/writer.py", line 208, in visit_node
    node.visit(self)
  File "androguard/androguard/decompiler/basic_blocks.py", line 299, in visit
    visitor.visit_catch_node(self)
  File "androguard/androguard/decompiler/writer.py", line 403, in visit_catch_node
    catch_node.visit_exception(self)
  File "androguard/androguard/decompiler/basic_blocks.py", line 305, in visit_exception
    visitor.write(get_type(self.catch_type))
  File "androguard/androguard/decompiler/util.py", line 184, in get_type
    if atype[0] == 'L':
TypeError: 'NoneType' object is not subscriptable
```

### System Information

- Androguard Version: master
- Python Version: 3.10.12 and 3.11.2
- Operating System: Both Linux x86_64 and arm64.

### Further Log Files and Output

I've had this issue pop up with multiple files and it's always been related to try/catch blocks.

After patching `decompiler.util.get_type` to return `?` if `atype` is `None`, Androguard printed 
the following:

```java
private static boolean isParserOutdated(org.xmlpull.v1.XmlPullParser p3)
{
    int v0 = 1;
    try {
        if ((p3 != 0) && ((p3.getEventType() != 3) && (p3.getEventType() != 1))) {
            v0 = 0;
        }
    } catch (?) {
    }
    return v0;
}
```

```java
public void send(int p3, android.os.Bundle p4)
{
    if (!this.mLocal) {
        android.support.v4.os.IResultReceiver v0_1 = this.mReceiver;
        try {
            if (v0_1 != null) {
                v0_1.send(p3, p4);
            }
        } catch (?) {
        }
        return;
    } else {
        android.support.v4.os.IResultReceiver v0_2 = this.mHandler;
        if (v0_2 == null) {
            this.onReceiveResult(p3, p4);
        } else {
            v0_2.post(new android.support.v4.os.ResultReceiver$MyRunnable(this, p3, p4));
        }
        return;
    }
}
```

I managed to trace the issue all the way to `decompiler.graph.Graph.add_catch_edge`. It turns 
out that some nodes enter the method with `catch_type` set to `None`.

After that I patched `decompiler.graph.make_node` to always call `set_catch_type` for both nodes 
before the call to `decompiler.graph.Graph.add_catch_edge`:

![Screenshot from 2024-09-24 00-43-04](https://github.com/user-attachments/assets/6e16c11b-5773-4aa1-903a-03e386bcb96a)

This fix was sufficient for most methods in the APK, but the loop eventually crashed because 
there appears to be another context that calls `decompiler.graph.Graph.add_catch_edge` without 
using `set_catch_type` at all.

I printed the state of both nodes upon entering `decompiler.graph.Graph.add_catch_edge` and it 
turns out that there are cases when only one has a non-empty `catch_type`:

```
e1.catch_type = None
e2.catch_type = 'Ljava/lang/Throwable;'
```

```
e1.catch_type = 'Ljava/lang/Throwable;'
e2.catch_type = None
```

After seeing that I added an extra section to `decompiler.graph.Graph.add_catch_edge` that 
ensures nodes inherit non-empty `catch_type` values from each other, i.e. `e1` would fetch from 
`e2` and vice versa:

![Screenshot from 2024-09-24 00-43-50](https://github.com/user-attachments/assets/53ad72d6-f068-4b6c-b482-5aa91030b05b)

Please correct me if I'm wrong, but I don't think there will ever be a scenario where `e1` and `e2` 
would have different non-empty values. I believe they are meant to be part of the same catch 
context, aren't they?

After both changes the source code printed without issues and the new exception classes appear to 
be a match with the values I found online:

https://androidx.tech/artifacts/appcompat/appcompat/1.6.0-source/androidx/appcompat/app/LayoutIncludeDetector.java.html

```java
private static boolean isParserOutdated(org.xmlpull.v1.XmlPullParser p3)
{
    int v0 = 1;
    try {
        if ((p3 != 0) && ((p3.getEventType() != 3) && (p3.getEventType() != 1))) {
            v0 = 0;
        }
    } catch (org.xmlpull.v1.XmlPullParserException) {
    }
    return v0;
}
```

```java
public void send(int p3, android.os.Bundle p4)
{
    if (!this.mLocal) {
        android.support.v4.os.IResultReceiver v0_1 = this.mReceiver;
        try {
            if (v0_1 != null) {
                v0_1.send(p3, p4);
            }
        } catch (android.os.RemoteException) {
        }
        return;
    } else {
        android.support.v4.os.IResultReceiver v0_2 = this.mHandler;
        if (v0_2 == null) {
            this.onReceiveResult(p3, p4);
        } else {
            v0_2.post(new android.support.v4.os.ResultReceiver$MyRunnable(this, p3, p4));
        }
        return;
    }
}
```

I pushed my changes here: #1080. I'd appreciate a review.

**Comment by erev0s** [comment]
great work once again @aitviid . Thank you
