### ISSUE TITLE
'VMAnalysis' object has no attribute '_VMAnalysis__vm'

### ISSUE THREAD

**Issue by zyrikby** [androguard/androguard#110]
If you create VMAnalysis object:
```python
a = apk.APK( TEST )
vm = DalvikVMFormat(a.get_dex())
vmx = VMAnalysis(vm)
```

you will get the following error:
```
Traceback (most recent call last):
  File "/home/yury/PROJECTS/ANDROGUARD/androguard/demos/apk_format_3.py", line 21, in <module>
    vmx = VMAnalysis(vm)
  File "/home/yury/PROJECTS/ANDROGUARD/androguard/androguard/core/analysis/analysis.py", line 1886, in __init__
    for i in self.__vm.get_all_fields():
AttributeError: 'VMAnalysis' object has no attribute '_VMAnalysis__vm'
```

**Comment by adesnos** [comment]
fixed
