### ISSUE TITLE
IOError when running androdd.py

### ISSUE THREAD

**Issue by F3real** [androguard/androguard#130]
When running `androdd.py -i app-debug.apk -o tmp` on Windows I get following error:
```python
Traceback (most recent call last):
  File "E:\TestAndroid\androguard-2.0\androdd.py", line 218, in <module>
    main(options, arguments)
  File "E:\TestAndroid\androguard-2.0\androdd.py", line 203, in main
    export_apps_to_format(options.input, a, options.output, options.limit, options.jar, options.decompiler, options.format)
  File "E:\TestAndroid\androguard-2.0\androdd.py", line 195, in export_apps_to_format
    with open(filename + ".ag", "w") as fd:
IOError: [Errno 22] invalid mode ('w') or filename: 'tmp/android/support/v4/BuildConfig/<init>--V.ag'
```

**Comment by F3real** [comment]
< and > are forbidden in filenames on windows

**Comment by reox** [comment]
Yes, this should be fixed. There are also other things which should be looked at:
* maximum filename size / path length
* not allowed extensions
* not allowed filenames or unicode chars (are there any?)
