### ISSUE TITLE
issue when run androdd.py

### ISSUE THREAD

**Issue by thinhnd8752** [androguard/androguard#131]
Hi all, I get the following error when i run androdd.py : 
```python
Traceback (most recent call last):
  File "androdd.py", line 242, in <module>
    main(options, arguments)
  File "androdd.py", line 226, in main
    a = Androguard([options.input])
NameError: global name 'Androguard' is not defined

**Comment by hallucino** [comment]
Yes please use the release here: https://github.com/androguard/androguard/releases

**Comment by adesnos** [comment]
Please use https://github.com/androguard/androguard/releases
