### ISSUE TITLE
androidd.py has error pydot.InvocationException: -11

### ISSUE THREAD

**Issue by victorchoy** [androguard/androguard#132]
When i decompile a apk,  an error happens.  I try two times.  It always stops at Dump Lcbd; h ()Z ... jpg ...  Exception list below.   Is thers some solutions?  Hope your help.

```
Dump Lcbd; h ()Z ... jpg ...
Traceback (most recent call last):
  File "/Users/victor/Documents/develop/github/v_androguard/androdd.py", line 218, in <module>
    main(options, arguments)
  File "/Users/victor/Documents/develop/github/v_androguard/androdd.py", line 203, in main
    export_apps_to_format(options.input, a, options.output, options.limit, options.jar, options.decompiler, options.format)
  File "/Users/victor/Documents/develop/github/v_androguard/androdd.py", line 180, in export_apps_to_format
    method2format(filename + "." + format, format, None, buff)
  File "/Users/victor/Documents/develop/github/v_androguard/androguard/core/bytecode.py", line 360, in method2format
    getattr(d, "write_" + _format.lower())(output)
  File "/usr/local/lib/python2.7/site-packages/pydot.py", line 1602, in <lambda>
    lambda path, f=frmt, prog=self.prog : self.write(path, format=f, prog=prog))
  File "/usr/local/lib/python2.7/site-packages/pydot.py", line 1696, in write
    dot_fd.write(self.create(prog, format))
  File "/usr/local/lib/python2.7/site-packages/pydot.py", line 1796, in create
    status, stderr_output) )
pydot.InvocationException: Program terminated with status: -11. stderr follows: []
```

**Comment by subho007** [comment]
@victorchoy can you tell us what exactly the command you have executed ?

**Comment by victorchoy** [comment]
$androdd.py -i  xxx  -o dir  -f jpg

**Comment by reox** [comment]
@victorchoy can you check with the current master branch? I changes some bits and this one could be fixed as well by now.

**Comment by reox** [comment]
This looks like a pydot error... without having the actual APK I can not do anything :/

If this error persists with the new version of androdd, please reopen!
