### ISSUE TITLE
newVMAnalysis class breaks elsim

### ISSUE THREAD

**Issue by androsex** [androguard/androguard#147]
Hi *,
The class "newVMAnalysis"[1] doesn't define "get_method_signature" method. Which is called by elsim_dalvik.py [2]

the traceback is following

Traceback (most recent call last):
  File "./androdiff.py", line 151, in <module>
    main(options, arguments)
  File "./androdiff.py", line 111, in main
    threshold, options.compressor)
  File "./elsim/elsim/elsim.py", line 155, in **init**
    self._init_similarity()
  File "./elsim/elsim/elsim.py", line 236, in _init_similarity
    self.filters[SIMILARITY_ELEMENTS][ j ][ k ] = self.filters[BASE][FILTER_SIM_METH](self.sim, j, k)
  File "./elsim/elsim/elsim_dalvik.py", line 86, in filter_sim_meth_basic
    ncd1, _ = sim.ncd( m1.checksum.get_signature(), m2.checksum.get_signature() )
  File "./elsim/elsim/elsim_dalvik.py", line 55, in get_signature
    self.signature = self.m1.vmx.get_method_signature( self.m1.m, predef_sign = DEFAULT_SIGNATURE ).get_string()
AttributeError: 'newVMAnalysis' object has no attribute 'get_method_signature'

thanks

[1] https://github.com/androguard/androguard/blob/master/androguard/core/analysis/analysis.py#L703
[2] https://github.com/androguard/androguard/blob/master/elsim/elsim/elsim_dalvik.py#L55

**Comment by reox** [comment]
Yes, elsim is at the moment completly broken and also was removed from androguard lately. I filter branched elsim from androguard (https://github.com/reox/elsim) and you can still check out an old version of androguard and use it with elsim - but of course you can not use the newest features of androguard then...
