### ISSUE TITLE
DAD dataflow tests are failing on py3

### ISSUE THREAD

**Issue by reox** [androguard/androguard#216]
because the hash of dictionaries is now randomized, the ordering of keys is not so deterministic as in python2.
I assume therefore those tests fail.

Need to check if this is really the case and probably adopt the testcases to just check for exsistence and not for ordering as well.
```
$ python androguard/decompiler/dad/tests/dataflow_test.py

.FF....

======================================================================

FAIL: testDefUseIfBool (__main__.DataflowTest)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/virtualenv/python3.6.0/lib/python3.6/site-packages/mock/mock.py", line 1305, in patched

    return func(*args, **keywargs)

  File "androguard/decompiler/dad/tests/dataflow_test.py", line 327, in testDefUseIfBool

    self.assertEqual(du, expected_du)

AssertionError: defaultdict(<class 'list'>, {(2, -1): [1,[85 chars][8]}) != {(0, 0): [7, 5], (0, 4): [8], (0, 5): [8][56 chars], 3]}

======================================================================

FAIL: testGroupVariablesGCD (__main__.DataflowTest)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "androguard/decompiler/dad/tests/dataflow_test.py", line 362, in testGroupVariablesGCD

    self.assertEqual(groups, expected_groups)

AssertionError: defaultdict(<class 'list'>, {'a': [([-1],[112 chars]])]}) != {'a': [([-1], [0])], 'b': [([-2], [1])], [83 chars]9])]}

----------------------------------------------------------------------

Ran 7 tests in 1.050s

FAILED (failures=2)

The command "python androguard/decompiler/dad/tests/dataflow_test.py" exited with 1.
```

I noticed, that one of the tests would actually work sometimes, so this is a strong indicator that it has to do with the hashes.

**Comment by adesnos** [comment]
Geoffroy, do you want to take a look or reassign to someone else ?

**Comment by reox** [comment]
For fun, I tested on pypy-5.3.1:
https://travis-ci.org/androguard/androguard/jobs/247450715#L320

It fails there for a similar reason.
