### ISSUE TITLE
androdd.py run error with arg '-f png'

### ISSUE THREAD

**Issue by feicong** [androguard/androguard#218]
```
$ ./androdd.py -i app-release.apk -o ./outjar -d --jar -f png
/Library/Python/2.7/site-packages/magic/identify.py:62: RuntimeWarning: Implicitly cleaning up <magic.api.LP_Cookie object at 0x10cf93170>
  CleanupWarning)
Dump information app-release.apk in ./outjar
Clean directory ./outjar
Decompilation ... End
Dump Landroid/support/annotation/CheckResult; suggest ()Ljava/lang/String; ... png ... Traceback (most recent call last):
  File "./androdd.py", line 220, in <module>
    main(options, arguments)
  File "./androdd.py", line 206, in main
    options.jar, options.decompiler, options.format)
  File "./androdd.py", line 180, in export_apps_to_format
    method2format(filename + "." + format, format, None, buff)
  File "/Users/android/git/androguard/androguard/core/bytecode.py", line 398, in method2format
    getattr(d, "write_" + _format.lower())(output)
AttributeError: 'list' object has no attribute 'write_png'
```

pydot and graphviz has already installed.

**Comment by zhufx** [comment]
I have the same issue , Is there any contributor can fix this？

**Comment by reox** [comment]
It seems androdd has some more problems. I have unicode related errors all over the place. I think I found most of them now but I get some OOM errors...
```
  File "androdd.py", line 220, in <module>
    main(options, arguments)
  File "androdd.py", line 206, in main
    options.jar, options.decompiler, options.format)
  File "androdd.py", line 180, in export_apps_to_format
    method2format(filename + "." + format, format, None, buff)
  File "/home/vagrant/androguard/androguard/core/bytecode.py", line 398, in method2format
    getattr(d, "write_" + _format.lower())(output)
  File "/usr/lib/python3/dist-packages/pydot.py", line 1746, in <lambda>
    lambda path, f=frmt, prog=self.prog: self.write(path, format=f, prog=prog)
  File "/usr/lib/python3/dist-packages/pydot.py", line 1851, in write
    fobj.write(self.create(prog, format))
  File "/usr/lib/python3/dist-packages/pydot.py", line 1961, in create
    status, stderr_output))
pydot.InvocationException: Program terminated with status: -11. stderr follows: dot: graph is too large for cairo-renderer bitmaps. Scaling by 0.596425 to fit
dot: failure to create cairo surface: out of memory
```

But never this one.
Can you share the APK or hashes? It might be a problem with a specific APK only...

**Comment by reox** [comment]
@feicong and @zhufx can you check if the fix supplied in #240 works for you?

**Comment by zhufx** [comment]
@reox OK, How do i get the code that fixed this issue ?

**Comment by reox** [comment]
you can use: `git clone https://github.com/reox/androguard.git -b reox-unicodeandrodd`to clone the branch where I commited the changes.

**Comment by zhufx** [comment]
@reox  It works very well ! Thank you!
