### ISSUE TITLE
AnalyzeAPK() for some APKs gives:  struct.error: unpack requires a bytes object of length 4

### ISSUE THREAD

**Issue by wdormann** [androguard/androguard#280]
### Describe what you wanted to do

When parsing https://play.google.com/store/apps/details?id=com.ovkuse.appsbunch with Androguard's androlyze.py, I get:  struct.error: unpack requires a bytes object of length 4
Some other apps give the same error:
org.iShia.iShia.Free
com.app.cp.blog8066
com.app.cp.blog2585
etc...

### Describe what you expected
Parse w/o error

### Describe what actually happened

Androguard version 3.1.0-dev
In [1]: a,d,dx = AnalyzeAPK('com.ovkuse.appsbunch.apk')
WARNING: invalid chunk type
NoneType
---------------------------------------------------------------------------
error                                     Traceback (most recent call last)
/usr/local/lib/python3.5/dist-packages/androguard-3.1.0.dev0-py3.5.egg/EGG-INFO/scripts/androlyze.py in <module>()
----> 1 a,d,dx = AnalyzeAPK('by_sha256/01/54/43/015443accccda1dbca5513ad8196a9c52870c8905b34985e0eb9c27a0220c6c2/com.ovkuse.appsbunch.apk')

/usr/local/lib/python3.5/dist-packages/androguard-3.1.0.dev0-py3.5.egg/androguard/misc.py in AnalyzeAPK(filename, session)
     42         data = fd.read()
     43
---> 44     session.add(filename, data)
     45     return session.get_objects_apk(filename)
     46

/usr/local/lib/python3.5/dist-packages/androguard-3.1.0.dev0-py3.5.egg/androguard/session.py in add(self, filename, raw_data, dx)
    152             digest = hashlib.sha256(raw_data).hexdigest()
    153             if ret == "APK":
--> 154                 apk_digest, apk = self.addAPK(filename, raw_data)
    155                 dex_files = list(apk.get_all_dex())
    156

/usr/local/lib/python3.5/dist-packages/androguard-3.1.0.dev0-py3.5.egg/androguard/session.py in addAPK(self, filename, data)
     72         digest = hashlib.sha256(data).hexdigest()
     73         androconf.debug("add APK:%s" % digest)
---> 74         apk = APK(data, True)
     75         self.analyzed_apk[digest] = [apk]
     76         self.analyzed_files[filename].append(digest)

/usr/local/lib/python3.5/dist-packages/androguard-3.1.0.dev0-py3.5.egg/androguard/core/bytecodes/apk.py in __init__(self, filename, raw, mode, magic_file, zipmodule, skip_analysis)
    199             for i in self.zip.namelist():
    200                 if i == "AndroidManifest.xml":
--> 201                     self.axml[i] = AXMLPrinter(self.zip.read(i))
    202                     try:
    203                         self.xml[i] = minidom.parseString(self.axml[i].get_buff())

/usr/local/lib/python3.5/dist-packages/androguard-3.1.0.dev0-py3.5.egg/androguard/core/bytecodes/apk.py in __init__(self, raw_buff)
   1574
   1575         while True and self.axml.is_valid():
-> 1576             _type = next(self.axml)
   1577
   1578             if _type == START_DOCUMENT:

/usr/local/lib/python3.5/dist-packages/androguard-3.1.0.dev0-py3.5.egg/androguard/core/bytecodes/apk.py in __next__(self)
   1254
   1255     def __next__(self):
-> 1256         self.doNext()
   1257         return self.m_event
   1258

/usr/local/lib/python3.5/dist-packages/androguard-3.1.0.dev0-py3.5.egg/androguard/core/bytecodes/apk.py in doNext(self)
   1302
   1303             self.buff.read(4)  # /*chunkSize*/
-> 1304             lineNumber = unpack('<L', self.buff.read(4))[0]
   1305             self.buff.read(4)  # 0xFFFFFFFF
   1306

error: unpack requires a bytes object of length 4

### System Information

- Androguard Version: master
- Python Version: 3.5.2
- Operating System

### Further Log Files and Output

The zip file checks out fine with "unzip -t"

**Comment by reox** [comment]
I think this is again an issue with packed manifest files. :/

**Comment by wdormann** [comment]
Attached is the AndroidManifest.xml file for com.ovkuse.appsbunch as it is extracted using apktool.

[AndroidManifest.xml.2.txt](https://github.com/androguard/androguard/files/1190594/AndroidManifest.xml.2.txt)

**Comment by reox** [comment]
It looks like this error happens if someone sets the style offset to some number but the style counter is zero, e.g. there are no styles.

I also added a fix for that in this branch: https://github.com/reox/androguard/tree/fix-axml-missing-ns
@wdormann can you check if this fixes it?

**Comment by wdormann** [comment]
I don't think that fixes anything.  I believe that I'm running what you suggest:
```
$ git branch
* axml_strange_header
  master
git remote show origin                                                                                                                                                                         * remote origin
  Fetch URL: https://github.com/reox/androguard.git
  Push  URL: https://github.com/reox/androguard.git
  HEAD branch: master
  Remote branches:
    axml_strange_header tracked
    decompiler-speed    tracked
    fix-271             tracked
    fix-277             tracked
    fix-axml-missing-ns tracked
    fix-get_methods     tracked
    master              tracked
    rewrite-magic       tracked
    speedtests          tracked
    testzip             tracked
  Local branches configured for 'git pull':
    axml_strange_header merges with remote axml_strange_header
    master              merges with remote master
  Local refs configured for 'git push':
    axml_strange_header pushes to axml_strange_header (up to date)
    master              pushes to master              (up to date)
$
```

But when I run AnalyzeAPK, I get the exact same symptoms:
```
a,d,dx = AnalyzeAPK('by_sha256/01/54/43/015443accccda1dbca5513ad8196a9c52870c8905b34985e0eb9c27a0220c6c2/com.ovkuse.appsbunch.apk')

<SNIP>

/home/wd/in/reox/androguard/androguard/core/bytecodes/apk.pyc in __init__(self, filename, raw, mode, magic_file, zipmodule, skip_analysis)
    200             for i in self.zip.namelist():
    201                 if i == "AndroidManifest.xml":
--> 202                     self.axml[i] = AXMLPrinter(self.zip.read(i))
    203                     try:
    204                         self.xml[i] = minidom.parseString(self.axml[i].get_buff())

/home/wd/in/reox/androguard/androguard/core/bytecodes/apk.pyc in __init__(self, raw_buff)
   1582
   1583         while True and self.axml.is_valid():
-> 1584             _type = next(self.axml)
   1585
   1586             if _type == START_DOCUMENT:

/usr/lib/python2.7/dist-packages/future/types/newobject.pyc in next(self)
     69     def next(self):
     70         if hasattr(self, '__next__'):
---> 71             return type(self).__next__(self)
     72         raise TypeError('newobject is not an iterator')
     73

/home/wd/in/reox/androguard/androguard/core/bytecodes/apk.pyc in __next__(self)
   1262
   1263     def __next__(self):
-> 1264         self.doNext()
   1265         return self.m_event
   1266

/home/wd/in/reox/androguard/androguard/core/bytecodes/apk.pyc in doNext(self)
   1310
   1311             self.buff.read(4)  # /*chunkSize*/
-> 1312             lineNumber = unpack('<L', self.buff.read(4))[0]
   1313             self.buff.read(4)  # 0xFFFFFFFF
   1314

error: unpack requires a string argument of length 4

In [2]:
```

Do you need a copy of an offending APK for your own testing?

**Comment by reox** [comment]
This is weird, I tested with the APKs from the inital report and it works for me... Maybe I got the wrong APK... Can you upload them somehow?

**Comment by wdormann** [comment]
These links should work:

error: unpack requires a string argument of length 4
https://drive.google.com/open?id=0BzrbzLF_CbEYTzRJd2lpQUFYWmc

xml.parsers.expat.ExpatError: unbound prefix: line 108, column 0
https://drive.google.com/open?id=0BzrbzLF_CbEYTi1pUkZJbGdwbW8

**Comment by reox** [comment]
Oh wait, did you used `axml_strange_header`? The changes for those two issues are not in this branch. Can you check against master of https://github.com/androguard/androguard ?
For the ovkuse app I get: Declared filesize does not match real size: 10356 vs 10364
and the shopgate should work fine now.

I'm not sure how to deal with the filesize thing, maybe parse the file until the declared size only?

**Comment by wdormann** [comment]
master of  https://github.com/androguard/androguard is now working.  I'm not sure what was going on with my testing before, as you can see that I was running axml_strange_header:

```
$ git branch
* axml_strange_header
  master
git remote show origin                                                                                                                                                                         * remote origin
  Fetch URL: https://github.com/reox/androguard.git
  Push  URL: https://github.com/reox/androguard.git
  HEAD branch: master
```


Anyway, master is working!

**Comment by reox** [comment]
👍 
I'll close the issue then! If you have more such non-working APKs, please report them!

**Comment by wdormann** [comment]
yeah, this cleared out a good chunk of them.  There are a few remaining classes of APKs that still fail, and I'll file ticket(s) for them.

**Comment by tryinglibrary** [comment]
Hi, I am finding exactly the same issue. I obtained apk files from my phone using adb. Then I use a,d,dx=analyzeAPK("target.apk") in a Windows PC and I get the same error described above. I downloaded and installed androguard yesterday. Any help please?

**Comment by reox** [comment]
Can you send us the samples and a full traceback?

**Comment by dj141999** [comment]
File "/app/andro.py", line 13, in extract_features
2020-04-17T07:04:58.269518+00:00 app[web.1]:     d = DalvikVMFormat(a.get_dex())
2020-04-17T07:04:58.269519+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/androguard/core/bytecodes/dvm.py", line 7643, in __init__
2020-04-17T07:04:58.269519+00:00 app[web.1]:     self._load(buff)
2020-04-17T07:04:58.269519+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/androguard/core/bytecodes/dvm.py", line 7649, in _load
2020-04-17T07:04:58.269520+00:00 app[web.1]:     self.__header = HeaderItem(0, self, ClassManager(None, self.config))
2020-04-17T07:04:58.269520+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/androguard/core/bytecodes/dvm.py", line 434, in __init__
2020-04-17T07:04:58.269521+00:00 app[web.1]:     self.magic = unpack("=Q", buff.read(8))[0]
2020-04-17T07:04:58.269525+00:00 app[web.1]: struct.error: unpack requires a buffer of 8 bytes


i am getting this error
