### ISSUE TITLE
PyASN1 errors due to version change?

### ISSUE THREAD

**Issue by reox** [androguard/androguard#286]
Looks like the build is failing due to a new versions?
```
======================================================================

ERROR: testAPKWrapper (__main__.APKTest)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "tests/test_apk.py", line 32, in testAPKWrapper

    self.assertIsNotNone(a.get_certificate(a.get_signature_name()))

  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/androguard/core/bytecodes/apk.py", line 841, in get_certificate

    message, _ = decode(pkcs7message)

  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/pyasn1/codec/ber/decoder.py", line 1008, in __call__

    stGetValueDecoder, self, substrateFun

  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/pyasn1/codec/ber/decoder.py", line 382, in valueDecoder

    component, head = decodeFun(head, asn1Spec)

  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/pyasn1/codec/ber/decoder.py", line 1008, in __call__

    stGetValueDecoder, self, substrateFun

  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/pyasn1/codec/ber/decoder.py", line 71, in valueDecoder

    value, _ = decodeFun(head, asn1Spec, tagSet, length)

  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/pyasn1/codec/ber/decoder.py", line 1008, in __call__

    stGetValueDecoder, self, substrateFun

  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/pyasn1/codec/ber/decoder.py", line 382, in valueDecoder

    component, head = decodeFun(head, asn1Spec)

  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/pyasn1/codec/ber/decoder.py", line 1008, in __call__

    stGetValueDecoder, self, substrateFun

  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/pyasn1/codec/ber/decoder.py", line 382, in valueDecoder

    component, head = decodeFun(head, asn1Spec)

  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/pyasn1/codec/ber/decoder.py", line 1015, in __call__

    '%s not in asn1Spec: %r' % (tagSet, asn1Spec)

PyAsn1Error: [0:32:16] not in asn1Spec: TagMap()
```

This version got installed: pyasn1-0.3.2-py2.py3-none-any.whl
before pyasn1-0.2.3-py2.py3-none-any.whl was used...

**Comment by reox** [comment]
this bug seems to be fixed in the master of pyasn1. that means we should disallow versions 0.3.1 and 0.3.2 for the future.
