### ISSUE TITLE
Install androguard as user with pip fails

### ISSUE THREAD

**Issue by reox** [androguard/androguard#309]
If you want to install androguard via pip as a non-root user it fails:
```
Exception:
Traceback (most recent call last):
  File "/home/reox/.local/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/reox/.local/lib/python2.7/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/home/reox/.local/lib/python2.7/site-packages/pip/req/req_set.py", line 778, in install
    requirement.uninstall(auto_confirm=True)
  File "/home/reox/.local/lib/python2.7/site-packages/pip/req/req_install.py", line 754, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/home/reox/.local/lib/python2.7/site-packages/pip/req/req_uninstall.py", line 115, in remove
    renames(path, new_path)
  File "/home/reox/.local/lib/python2.7/site-packages/pip/utils/__init__.py", line 267, in renames
    shutil.move(old, new)
  File "/usr/lib/python2.7/shutil.py", line 317, in move
    os.unlink(src)
OSError: [Errno 13] Keine Berechtigung: '/usr/share/androguard/androguard.ico'
```

Probably we need to adopt the path then?

**Comment by reox** [comment]
this should be fixed now
