### ISSUE TITLE
No attribute map_item in data_off_obj

### ISSUE THREAD

**Issue by reox** [androguard/androguard#317]
### Describe what you wanted to do

Serveral files from F-Droid:
am.zoom.mbrowser_12.apk
android.androidVNC_13.apk
android.game.prboom_31.apk
...

### Describe what actually happened
```
Traceback (most recent call last):
  File "test_androguard_fdroid.py", line 115, in main
    x()
  File "C:\Program Files\Anaconda3\lib\site-packages\androguard\core\bytecodes\dvm.py", line 7777, in save
    length = i.get_length()
  File "C:\Program Files\Anaconda3\lib\site-packages\androguard\core\bytecodes\dvm.py", line 502, in get_length
    return len(self.get_raw())
  File "C:\Program Files\Anaconda3\lib\site-packages\androguard\core\bytecodes\dvm.py", line 499, in get_raw
    return self.get_obj()
  File "C:\Program Files\Anaconda3\lib\site-packages\androguard\core\bytecodes\dvm.py", line 471, in get_obj
    self.data_size = len(self.data_off_obj.map_item)
```

and similar:
```
Traceback (most recent call last):
  File "test_androguard_fdroid.py", line 115, in main
    x()
  File "C:\Program Files\Anaconda3\lib\site-packages\androguard\core\bytecodes\dvm.py", line 7777, in save
    length = i.get_length()
  File "C:\Program Files\Anaconda3\lib\site-packages\androguard\core\bytecodes\dvm.py", line 502, in get_length
    return len(self.get_raw())
  File "C:\Program Files\Anaconda3\lib\site-packages\androguard\core\bytecodes\dvm.py", line 499, in get_raw
    return self.get_obj()
  File "C:\Program Files\Anaconda3\lib\site-packages\androguard\core\bytecodes\dvm.py", line 471, in get_obj
    self.data_size = len(self.data_off_obj.map_item)
AttributeError: 'CodeItem' object has no attribute 'map_item'
```
(from app.varlorg.unote_7.apk)

### System Information

- Androguard Version: master
- Python Version: 3.6
- Operating System: windows

**Comment by reox** [comment]
well, I should know that I already reportet that -.-
