### ISSUE TITLE
dvm.save() is broken

### ISSUE THREAD

**Issue by palanik1** [androguard/androguard#32]
I tried running crackme_dexlabs_patch.py from the demos folder and I get the following error

File "crackme_dexlabs_patch.py", line 59, in <module>
    new_dex = vm.save()
  File "/home/android/androguard/androguard/core/bytecodes/dvm.py", line 7445, in save
    length = i.get_length()
  File "/home/android/androguard/androguard/core/bytecodes/dvm.py", line 512, in get_length
    return len(self.get_raw())
  File "/home/android/androguard/androguard/core/bytecodes/dvm.py", line 509, in get_raw
    return self.get_obj()
  File "/home/android/androguard/androguard/core/bytecodes/dvm.py", line 505, in get_obj
    pack("=I", self.data_size) +            \
struct.error: integer out of range for 'I' format code

Appreciate any help in this regard.

Thanks,
Palani.

**Comment by adesnos** [comment]
Yep :(

**Comment by reox** [comment]
Fails now with another error:
```
Traceback (most recent call last):
  File "demos/create_invalid_dex.py", line 25, in <module>
    new_dex = vm.save()
  File "/usr/local/lib/python2.7/dist-packages/androguard-3.1.0.dev0-py2.7.egg/androguard/core/bytecodes/dvm.py", line 7754, in save
    length = i.get_length()
  File "/usr/local/lib/python2.7/dist-packages/androguard-3.1.0.dev0-py2.7.egg/androguard/core/bytecodes/dvm.py", line 7003, in get_length
    length += i.get_size()
  File "/usr/local/lib/python2.7/dist-packages/androguard-3.1.0.dev0-py2.7.egg/androguard/core/bytecodes/dvm.py", line 6933, in get_size
    length += self.code.get_length()
  File "/usr/local/lib/python2.7/dist-packages/androguard-3.1.0.dev0-py2.7.egg/androguard/core/bytecodes/dvm.py", line 6668, in get_length
    return len(self.get_raw())
  File "/usr/local/lib/python2.7/dist-packages/androguard-3.1.0.dev0-py2.7.egg/androguard/core/bytecodes/dvm.py", line 6660, in get_raw
    return b''.join(i.get_raw() for i in self.get_instructions())
TypeError: sequence item 6: expected string, bytearray found
```
