### ISSUE TITLE
androguard badzipfile error

### ISSUE THREAD

**Issue by nidhi-naviranj** [androguard/androguard#362]
Following error generated while parsing an apk. 
How to handle it?
please help!

Traceback (most recent call last):
  File "C:\Python27\finalextract.py", line 11, in <module>
    a=APK(f)
  File "C:\Python27\lib\site-packages\androguard\core\bytecodes\apk.py", line 190, in __init__
    self.axml[i] = AXMLPrinter(self.zip.read(i))
  File "C:\Python27\lib\zipfile.py", line 935, in read
    return self.open(name, "r", pwd).read()
  File "C:\Python27\lib\zipfile.py", line 630, in read
    data = self.read1(n)
  File "C:\Python27\lib\zipfile.py", line 692, in read1
    self._update_crc(data, eof=eof)
  File "C:\Python27\lib\zipfile.py", line 647, in _update_crc
    raise BadZipfile("Bad CRC-32 for file %r" % self.name)
BadZipfile: Bad CRC-32 for file 'AndroidManifest.xml'

**Comment by reox** [comment]
this error means that the zipfile itself is broken.
try unpack the file with unzip and see what it says. usually it will tell you the same.

If unzip gives you no error, the python zipfile implementation might have some troubles.
in this case, please share the zip file with us, so we can have a look!
