### ISSUE TITLE
Errors raised during valid APK decoding

### ISSUE THREAD

**Issue by U039b** [androguard/androguard#392]
We use **Androguard** in [εxodus](https://github.com/Exodus-Privacy/exodus) and [εxodus standalone](https://github.com/Exodus-Privacy/exodus-standalone) and it appears that **Androguard** is unable to decode some APKs. 

### What I wanted to do
In εxodus, we need to list Java classes contained into a given APK. To do so, we load, decode and call `get_classes_names()` method.
- This issue can be reproduced by decoding [this APK](https://framadrop.org/r/MWIlNfShVH#7PqXXozRgvcO0W3gslUt6ERxSk2RDMUdytxr8oq3wrU=)

### Error log
```
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/home/exodus/exodus/venv/lib/python3.5/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/home/exodus/exodus/venv/lib/python3.5/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/exodus/exodus/venv/lib/python3.5/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/exodus/exodus/venv/lib/python3.5/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/home/exodus/exodus/exodus/reports/management/commands/refreshstaticanalysis.py", line 76, in handle
    static_analysis.save_embedded_classes_in_file(fp.name)
  File "/home/exodus/exodus/exodus/exodus/core/static_analysis.py", line 103, in save_embedded_classes_in_file
    f.write('\n'.join(self.get_embedded_classes()))
  File "/home/exodus/exodus/exodus/exodus/core/static_analysis.py", line 94, in get_embedded_classes
    self.decode_apk()
  File "/home/exodus/exodus/exodus/exodus/core/static_analysis.py", line 51, in decode_apk
    self.decoded = DalvikVMFormat(self.apk)
  File "/home/exodus/exodus/venv/lib/python3.5/site-packages/androguard/core/bytecodes/dvm.py", line 7567, in __init__
    self._load(buff)
  File "/home/exodus/exodus/venv/lib/python3.5/site-packages/androguard/core/bytecodes/dvm.py", line 7578, in _load
    self.map_list = MapList(self.CM, self.__header.map_off, self)
  File "/home/exodus/exodus/venv/lib/python3.5/site-packages/androguard/core/bytecodes/dvm.py", line 7448, in __init__
    mi.parse()
  File "/home/exodus/exodus/venv/lib/python3.5/site-packages/androguard/core/bytecodes/dvm.py", line 7045, in parse
    for i in range(0, self.size)]
  File "/home/exodus/exodus/venv/lib/python3.5/site-packages/androguard/core/bytecodes/dvm.py", line 7045, in <listcomp>
    for i in range(0, self.size)]
  File "/home/exodus/exodus/venv/lib/python3.5/site-packages/androguard/core/bytecodes/dvm.py", line 1767, in __init__
    self.value = EncodedArray(buff, cm)
  File "/home/exodus/exodus/venv/lib/python3.5/site-packages/androguard/core/bytecodes/dvm.py", line 1425, in __init__
    self.values.append(EncodedValue(buff, cm))
  File "/home/exodus/exodus/venv/lib/python3.5/site-packages/androguard/core/bytecodes/dvm.py", line 1492, in __init__
    self.value = cm.get_raw_string(id)
  File "/home/exodus/exodus/venv/lib/python3.5/site-packages/androguard/core/bytecodes/dvm.py", line 7260, in get_raw_string
    return self.__strings_off[off].get()
  File "/home/exodus/exodus/venv/lib/python3.5/site-packages/androguard/core/bytecodes/dvm.py", line 1865, in get
    return s.encode("UTF-16", "surrogatepass").decode("UTF-16")
UnicodeDecodeError: 'utf-16-le' codec can't decode bytes in position 38-39: illegal UTF-16 surrogate
```

### System Information

- Androguard Version: master
- Python Version: 3.5.3
- Operating System: Debian Stretch

### Other errors which occurred during decoding
```
Reached a NAMESPACE_END without having the namespace stored before? Prefix ID: 37, URI ID: 188
```
```
Styles Offset given, but styleCount is zero.
```

[Complete error log](https://github.com/androguard/androguard/files/1591158/androguard_errors.txt)

**Comment by reox** [comment]
thanks, i can confirm that! looks like the new mutf-8 implementation, still has some issues...

**Comment by reox** [comment]
okay, this is the string:

```
from androguard.core.bytecodes.mutf8 import decode
import binascii
data = binascii.unhexlify("c0807fc2add880d89cdb9ddc8fe19a80e1a08ee28080e280a8e2819fe281a6e281a7e281a8e281a9e281aae38080eda080efbbbfefbfb9efbfba")
decode(data)
```
gives:
```
u'\x00\x7f\xad\u0600\u061c\u06dd\u070f\u1680\u180e\u2000\u2028\u205f\u2066\u2067\u2068\u2069\u206a\u3000\ud800\ufeff\ufff9\ufffa'
```

now, encode with UTF-16/surrogatepass:
```
'\xff\xfe\x00\x00\x7f\x00\xad\x00\x00\x06\x1c\x06\xdd\x06\x0f\x07\x80\x16\x0e\x18\x00 ( _ f g h i j \x000\x00\xd8\xff\xfe\xf9\xff\xfa\xff'
```

but this can not be decoded as utf16.

Not sure how to deal with such strings.
A quick fix would be something like this:
```
diff --git a/androguard/core/bytecodes/dvm.py b/androguard/core/bytecodes/dvm.py
index 97bfff4..e0a2855 100644
--- a/androguard/core/bytecodes/dvm.py
+++ b/androguard/core/bytecodes/dvm.py
@@ -1862,7 +1862,11 @@ class StringDataItem:
         assert len(s) == self.utf16_size, "UTF16 Length does not match!"
         # We need to escape surrogates and other stuff that might not be
         # printable...
-        return s.encode("UTF-16", "surrogatepass").decode("UTF-16")
+        nstr = s.encode("UTF-16", "surrogatepass")
+        try:
+            return nstr.decode("UTF-16")
+        except UnicodeDecodeError:
+            return nstr.decode("UTF-16", "surrogateescape")
 
     def show(self):
         bytecode._PrintSubBanner("String Data Item")
```

But maybe there is a better solution? It would be interesting to see the source code or what the string should be in Java. Maybe we should try to reproduce exactly that.

**Comment by U039b** [comment]
@reox I do not know which string you are talking about :-S but I provided the APK causing this issue (https://framadrop.org/r/MWIlNfShVH#7PqXXozRgvcO0W3gslUt6ERxSk2RDMUdytxr8oq3wrU=). I can provide all the APK causing decoding errors.

**Comment by reox** [comment]
the string is already out of the provided apk, but if you have more failing strings, please provide them as well.
Can you test if #393 will fix the issues? If you see log messages like `Error decoding UTF16 string with IDX ...` please provide them as well!

**Comment by U039b** [comment]
Here is the complete log:
```
╰─$ python exodus.py hsbc.apk
loading the apk
loading trackers signatures from Exodus
decoding the apk
Error decoding UTF16 string with IDX 5651122 and hexdata 'b'c0807fc2add880d89cdb9ddc8fe19a80e1a08ee28080e280a8e2819fe281a6e281a7e281a8e281a9e281aae38080eda080efbbbfefbfb9efbfba''. Fallback to surrogateescape string.
Traceback (most recent call last):
  File "[edited]/exodus-standalone/venv/lib/python3.5/site-packages/androguard/core/bytecodes/dvm.py", line 1869, in get
    return nstr.decode("UTF-16")
UnicodeDecodeError: 'utf-16-le' codec can't decode bytes in position 38-39: illegal UTF-16 surrogate

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "exodus.py", line 154, in <module>
    analysis.decode_apk()
  File "exodus.py", line 43, in decode_apk
    self.decoded = DalvikVMFormat(self.apk)
  File "[edited]/exodus-standalone/venv/lib/python3.5/site-packages/androguard/core/bytecodes/dvm.py", line 7572, in __init__
    self._load(buff)
  File "[edited]/exodus-standalone/venv/lib/python3.5/site-packages/androguard/core/bytecodes/dvm.py", line 7583, in _load
    self.map_list = MapList(self.CM, self.__header.map_off, self)
  File "[edited]/exodus-standalone/venv/lib/python3.5/site-packages/androguard/core/bytecodes/dvm.py", line 7453, in __init__
    mi.parse()
  File "[edited]/exodus-standalone/venv/lib/python3.5/site-packages/androguard/core/bytecodes/dvm.py", line 7052, in parse
    for i in range(0, self.size)]
  File "[edited]/exodus-standalone/venv/lib/python3.5/site-packages/androguard/core/bytecodes/dvm.py", line 7052, in <listcomp>
    for i in range(0, self.size)]
  File "[edited]/exodus-standalone/venv/lib/python3.5/site-packages/androguard/core/bytecodes/dvm.py", line 1769, in __init__
    self.value = EncodedArray(buff, cm)
  File "[edited]/exodus-standalone/venv/lib/python3.5/site-packages/androguard/core/bytecodes/dvm.py", line 1427, in __init__
    self.values.append(EncodedValue(buff, cm))
  File "[edited]/exodus-standalone/venv/lib/python3.5/site-packages/androguard/core/bytecodes/dvm.py", line 1494, in __init__
    self.value = cm.get_raw_string(id)
  File "[edited]/exodus-standalone/venv/lib/python3.5/site-packages/androguard/core/bytecodes/dvm.py", line 7264, in get_raw_string
    return self.__strings_off[off].get()
  File "[edited]/exodus-standalone/venv/lib/python3.5/site-packages/androguard/core/bytecodes/dvm.py", line 1872, in get
    return nstr.decode("UTF-16", "surrogateescape")
UnicodeDecodeError: 'utf-16-le' codec can't decode bytes in position 38-39: illegal UTF-16 surrogate

```

**Comment by U039b** [comment]
`AnalyzeAPK()` systematically fails with the APKs I have. All the APKs are downloaded from Google Play.
```
AttributeError: 'NoneType' object has no attribute 'get_method_analysis'
```

**Comment by reox** [comment]
thanks again!
looks like this is also different in python3... 

for the get_method_analysis, can you send me the complete log?

**Comment by reox** [comment]
As far as I understand the MUTF8 coding, this should be a Java code that produces this string:
```
class Str{

    public static void main(String args[]){

        String x = "\u0000\u007f\u00ad\u0600\u061c\u070f\u1680\u180e\u2000\u2028\u205f\u2066\u2067\u2068\u2069\u206a\u3000\ud800\ufeff\ufff9\ufffa";

        System.out.println(x);
    }
}
```

You can compile it and it will work fine...
As it matches the UTF16_size in the dexfile (both 22), I suspect this is the actual output we want somehow...

The question is further: Internally, no decoding/encoding is required to work. Everything you need to do is to call mutf8.decode and you have a unicode aware string that will work internally. The problem is always that you like to print the string somehow, somewhere... Then the question is how we should proceed with such strings. What is the wished outcome? In my opinion, the string should look like as it was a Java string, i.e. with 2 byte unicode escape sequences: https://docs.oracle.com/javase/specs/jls/se7/html/jls-3.html#jls-3.3

So the question is, if this resulting string should maybe only include chars from the ASCII table - i.e. everything that can be printed in ascii will be printed, and everything else is escaped.
This can be achieved using the `unicode_escape` encoder: https://docs.python.org/2/library/codecs.html#python-specific-encodings
But again here is a small drawback: in py2 a `str` is produced. In py3 a `bytes` object.
Interesstingly, both can now be decoded with `utf-16` and will produce some output (which is also equal in both versions...).

I just did this now in #393 - maybe you can give it a try?

**Comment by U039b** [comment]
Error log for `UTF-16` issue
```
╰─$ ./venv/bin/androlyze.py -s
Androguard version 3.1.0
In [1]: from androguard.core.androconf import show_logging

In [2]:  import logging
   ...:

In [3]: show_logging(logging.WARNING)

In [4]: a,d,dx = AnalyzeAPK("./hsbc.apk")
---------------------------------------------------------------------------
UnicodeDecodeError                        Traceback (most recent call last)
~/Make/exodus-standalone/venv/bin/androlyze.py in <module>()
----> 1 a,d,dx = AnalyzeAPK("./hsbc.apk")

~/Make/exodus-standalone/venv/lib/python3.5/site-packages/androguard/misc.py in AnalyzeAPK(_file, session, raw)
     50             filename = _file
     51
---> 52     digest = session.add(filename, data)
     53     return session.get_objects_apk(filename, digest)
     54

~/Make/exodus-standalone/venv/lib/python3.5/site-packages/androguard/session.py in add(self, filename, raw_data, dx)
    164             dx = self.analyzed_vms.get(digest)
    165             for dex in dex_files:
--> 166                 _, d, dx = self.addDEX(filename, dex, dx)
    167         elif ret == "DEX":
    168             digest, d, _ = self.addDEX(filename, raw_data)

~/Make/exodus-standalone/venv/lib/python3.5/site-packages/androguard/session.py in addDEX(self, filename, data, dx)
     98
     99         log.debug("Parsing format ...")
--> 100         d = DalvikVMFormat(data)
    101         log.debug("added DEX:%s" % digest)
    102

~/Make/exodus-standalone/venv/lib/python3.5/site-packages/androguard/core/bytecodes/dvm.py in __init__(self, buff, decompiler, config, using_api)
   7566
   7567         self._preload(buff)
-> 7568         self._load(buff)
   7569
   7570     def _preload(self, buff):

~/Make/exodus-standalone/venv/lib/python3.5/site-packages/androguard/core/bytecodes/dvm.py in _load(self, buff)
   7577             log.warning("no map list ...")
   7578         else:
-> 7579             self.map_list = MapList(self.CM, self.__header.map_off, self)
   7580
   7581             self.classes = self.map_list.get_item_type("TYPE_CLASS_DEF_ITEM")

~/Make/exodus-standalone/venv/lib/python3.5/site-packages/androguard/core/bytecodes/dvm.py in __init__(self, cm, off, buff)
   7447
   7448         for mi in ordered:
-> 7449             mi.parse()
   7450
   7451             c_item = mi.get_item()

~/Make/exodus-standalone/venv/lib/python3.5/site-packages/androguard/core/bytecodes/dvm.py in parse(self)
   7021
   7022         elif TYPE_MAP_ITEM[self.type] == "TYPE_ANNOTATION_ITEM":
-> 7023             self.item = [AnnotationItem(buff, cm) for i in range(0, self.size)]
   7024
   7025         elif TYPE_MAP_ITEM[self.type] == "TYPE_ANNOTATION_SET_ITEM":

~/Make/exodus-standalone/venv/lib/python3.5/site-packages/androguard/core/bytecodes/dvm.py in <listcomp>(.0)
   7021
   7022         elif TYPE_MAP_ITEM[self.type] == "TYPE_ANNOTATION_ITEM":
-> 7023             self.item = [AnnotationItem(buff, cm) for i in range(0, self.size)]
   7024
   7025         elif TYPE_MAP_ITEM[self.type] == "TYPE_ANNOTATION_SET_ITEM":

~/Make/exodus-standalone/venv/lib/python3.5/site-packages/androguard/core/bytecodes/dvm.py in __init__(self, buff, cm)
   1707
   1708         self.visibility = get_byte(buff)
-> 1709         self.annotation = EncodedAnnotation(buff, cm)
   1710
   1711     def get_visibility(self):

~/Make/exodus-standalone/venv/lib/python3.5/site-packages/androguard/core/bytecodes/dvm.py in __init__(self, buff, cm)
   1641         self.elements = []
   1642         for i in range(0, self.size):
-> 1643             self.elements.append(AnnotationElement(buff, cm))
   1644
   1645     def get_type_idx(self):

~/Make/exodus-standalone/venv/lib/python3.5/site-packages/androguard/core/bytecodes/dvm.py in __init__(self, buff, cm)
   1589
   1590         self.name_idx = readuleb128(buff)
-> 1591         self.value = EncodedValue(buff, cm)
   1592
   1593     def get_name_idx(self):

~/Make/exodus-standalone/venv/lib/python3.5/site-packages/androguard/core/bytecodes/dvm.py in __init__(self, buff, cm)
   1510             self.value = cm.get_field(id)
   1511         elif self.value_type == VALUE_ARRAY:
-> 1512             self.value = EncodedArray(buff, cm)
   1513         elif self.value_type == VALUE_ANNOTATION:
   1514             self.value = EncodedAnnotation(buff, cm)

~/Make/exodus-standalone/venv/lib/python3.5/site-packages/androguard/core/bytecodes/dvm.py in __init__(self, buff, cm)
   1425         self.values = []
   1426         for i in range(0, self.size):
-> 1427             self.values.append(EncodedValue(buff, cm))
   1428
   1429     def get_size(self):

~/Make/exodus-standalone/venv/lib/python3.5/site-packages/androguard/core/bytecodes/dvm.py in __init__(self, buff, cm)
   1492             id, self.raw_value = self._getintvalue(buff.read(self.value_arg +
   1493                                                              1))
-> 1494             self.value = cm.get_raw_string(id)
   1495         elif self.value_type == VALUE_TYPE:
   1496             id, self.raw_value = self._getintvalue(buff.read(self.value_arg +

~/Make/exodus-standalone/venv/lib/python3.5/site-packages/androguard/core/bytecodes/dvm.py in get_raw_string(self, idx)
   7258
   7259         try:
-> 7260             return self.__strings_off[off].get()
   7261         except KeyError:
   7262             log.warning("unknown string item @ 0x%x(%d)" % (off, idx))

~/Make/exodus-standalone/venv/lib/python3.5/site-packages/androguard/core/bytecodes/dvm.py in get(self)
   1866         # unicode_escape produces a string which is printable
   1867         # Then we decode that one as UTF-16
-> 1868         return s.encode("unicode_escape").decode("utf-16")
   1869
   1870     def show(self):

UnicodeDecodeError: 'utf-16-le' codec can't decode byte 0x3c in position 0: truncated data
```
BTW, if your new fix, Androguard is unable to decode APKs it was able to decode before.

**Comment by reox** [comment]
Thanks for testing!

Okay, I'm still not entirely sure what to do, but maybe the string should be decoded as ascii?
I just pushed that change.

**Comment by reox** [comment]
@subho007 do you have a good idea how we should deal with the unicode strings?

**Comment by reox** [comment]
The problem is also the following: someone might have stored some data in a string, which is not exactly unicode. For example such a thing:
```
>>> (chr((0b110110 << 10) | 0b1010110011) + chr(0x0000)).encode("UTF-16", "surrogatepass").decode("UTF-16")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeDecodeError: 'utf-16-le' codec can't decode bytes in position 2-3: illegal UTF-16 surrogate
```

So, the approach of decoding everything as UTF-16 works only if there are actual utf16 strings stored... This is exactly the problem with the given string:
0xd800 is treated as an high surrogate, but the following 0xfeff is not a low surrogate.

**Comment by reox** [comment]
@androguard/external-contributors anyone has an idea how to deal with this problem?
Here is a short recap:
* Internally, we can use unicode strings, no matter what is in there. In my opinion, the MUTF8 decoder works correctly in this respect.
* Not all strings are well behaved strings, ie if only a sole high or low surrogate is passed, the decoding will not work
* To be able to print strings, we need to merge surrogate pairs into a single 32bit character, ie `\uD853\uDF5C` must be written as `\u0024F5C` to be printable. Both `\uD853` and `\uDF5C` can never be printed.
The interesting thing is, that it will work in Java:
```
class Test{
        public static void main(String[] args){
                String s = "\uD853";
                System.out.println(s);
        }
}
```
Is a valid program and will compile and run.

**Comment by reox** [comment]
I wrote a function that will merge complete surrogates into 32bit chars and escape lonely surrogates by an ascii sequence.

I think this is the best solution...

**Comment by reox** [comment]
@U039b I pushed the changes to master. Can you test if it works now?

**Comment by U039b** [comment]
Hi @reox! 
Why do not add automatic tests? I can give you APKs which cause this error.

**Comment by reox** [comment]
tests are here: https://github.com/androguard/androguard/blob/master/tests/test_strings.py :)

the problem with testing whole APKs is, that it is very slow and we might have license problems - See also #257 

I would like to set up an extra repo where a lot (hundrets to thousands) of APKs are stored, which can be used for testing. I have something similar here for personal use but it takes some weeks for a full test run... For sure this can not be implemented as a CI process unfortunately.

**Comment by U039b** [comment]
Okay, if you need more APKs, ask me: https://reports.exodus-privacy.eu.org/reports/apps/
I will test your patch and let you know.
Q: does **androguard** supports multiple `DEX` files?

**Comment by reox** [comment]
> Q: does androguard support multiple DEX files?

yes! They are "bundled" in the Analysis object.
If you use `AnalyzeAPK` it will do the correct thing and return the `APK` object, a list of `DalvikVMFormat` and a single `Analysis` object.

**Comment by U039b** [comment]
Thank you for your answer and for your patch: no more decoding error :+1:

**Comment by reox** [comment]
I'm glad to hear that! If you have any other issues please report them.

**Comment by U039b** [comment]
I will ;-)
