### ISSUE TITLE
runing androaxml.py failed

### ISSUE THREAD

**Issue by gnaixx** [androguard/androguard#394]
running androaxml.py but have some error

- Androguard Version: master
- Python Version: 3.6.2
- Operating System: OSX EI Capitan 10.11.6

### Further Log Files and Output
```bash
➜ androaxml.py -i app-debug.apk
Traceback (most recent call last):
  File "/usr/local/bin/androaxml.py", line 85, in <module>
    main(options, arguments)
  File "/usr/local/bin/androaxml.py", line 56, in main
    buff = a.get_android_manifest_xml().toprettyxml(encoding="utf-8")
AttributeError: 'lxml.etree._Element' object has no attribute 'toprettyxml'
```

**Comment by ksg97031** [comment]
https://github.com/androguard/androguard/pull/399 check pls

**Comment by reox** [comment]
should be fixed, thanks to @ksg97031 !
