### ISSUE TITLE
giving -o to androaxml crashes on TypeError

### ISSUE THREAD

**Issue by eighthave** [androguard/androguard#419]
Looks like a remnant of the py3 port:

```console
$ androaxml -i ./examples/android/TestsAndroguard/bin/TestActivity.apk -o /dev/null
Traceback (most recent call last):
  File "/usr/bin/androaxml", line 87, in <module>
    main(options, arguments)
  File "/usr/bin/androaxml", line 69, in main
    fd.write(buff)
  File "/usr/lib/python3.5/codecs.py", line 718, in write
    return self.writer.write(data)
  File "/usr/lib/python3.5/codecs.py", line 376, in write
    data, consumed = self.encode(object, self.errors)
TypeError: Can't convert 'bytes' object to str implicitly
```

androguard 3.1.0rc1 on Ubuntu/xenial.

**Comment by reox** [comment]
yeah, I never looked at those tools as I have a metric ton of own ones :D 

I'll have a look at the tools!

**Comment by eighthave** [comment]
Something like this in the travis setup would catch them:

```yaml
script:
  - for f in `find -name \*.apk`; do
       ./androaxml.py -i $f > /dev/null;
       ./androaxml.py -i $f -o /dev/null; done
```

**Comment by reox** [comment]
lets see what #421 does :D
