### ISSUE TITLE
Support Android v2 Signature

### ISSUE THREAD

**Issue by reox** [androguard/androguard#425]
There is a new way of doing signing: The signature is stored inside a section in the ZIP file.

**Comment by reox** [comment]
I started with some v2 code here: #427

**Comment by reox** [comment]
@eighthave can you hint me with some APKs that are signed only with v2 and with v1 and v2 _and_ can be included in the androguard repo for testing purposes?

**Comment by eighthave** [comment]
I don't any test APKs, but they should be easy to generate.  Just take any unsigned APK, and use `apksigner` from Debian or _build-tools-27.0.3_.  It has v1-only, v2-only, and v1+v2 options when signing.

**Comment by reox** [comment]
mhh yes, this looks like the easiest option... Do you know how to generate keys that apktool understands? I tried with:
```
$ openssl req -newkey rsa:2048 -nodes -keyout key.pem -x509 -days 36500 -out certificate.pem
$ apksigner sign --key key.pem --cert certificate.pem --v1-signing-enabled --v2-signing-enabled --v1-signer-name ANDROGUARD TestActivity_unsigned.apk 
Failed to load signer "signer #1"
java.security.spec.InvalidKeySpecException: Failed to load PKCS #8 encoded private key from key.pem
	at com.android.apksigner.ApkSignerTool$SignerParams.loadPrivateKeyAndCertsFromFiles(ApkSignerTool.java:881)
	at com.android.apksigner.ApkSignerTool$SignerParams.loadPrivateKeyAndCerts(ApkSignerTool.java:648)
	at com.android.apksigner.ApkSignerTool$SignerParams.access$500(ApkSignerTool.java:600)
	at com.android.apksigner.ApkSignerTool.sign(ApkSignerTool.java:255)
	at com.android.apksigner.ApkSignerTool.main(ApkSignerTool.java:88)
Caused by: java.security.spec.InvalidKeySpecException: Not an RSA, EC, or DSA private key
	at com.android.apksigner.ApkSignerTool$SignerParams.loadPkcs8EncodedPrivateKey(ApkSignerTool.java:938)
	at com.android.apksigner.ApkSignerTool$SignerParams.loadPrivateKeyAndCertsFromFiles(ApkSignerTool.java:879)
	... 4 more

```

But it looks like it does not work...

**Comment by reox** [comment]
....
okay you need to use DER encoding for the key as well:

```
openssl pkcs8 -topk8 -inform PEM -outform DER -in key.pem -out priv.key -nocrypt
```

**Comment by reox** [comment]
This raises a question now: If a file is only signed with v2 but the min-sdk-level is <24, this means the v2 signature is actually bogus?

**Comment by eighthave** [comment]
The signature might be valid, but it won't work on <24 since it'll be
like an unsigned APK.  There is a similar effect with v1-signing an APK
using SHA-256 on <18.  SHA-256 support was added in android-18.  So
that'll be a valid signature, but it'll always fail on <18.

**Comment by reox** [comment]
okay good to know! We should start with some validation module that has all this information...

**Comment by eighthave** [comment]
FYI, if you want lots of test APKs, there are many included in the _apksigner_ git repo:

* https://android.googlesource.com/platform/tools/apksig/+/android-8.1.0_r14/src/test/resources/com/android/apksig

**Comment by reox** [comment]
nice!

```
v2-only-apk-sig-block-size-mismatch.apk, package: 'android.appsecurity.cts.tinyapp'
Is signed v1: False
Traceback (most recent call last):
  File "androsign.py", line 58, in <module>
    main()
  File "androsign.py", line 39, in main
    print("Is signed v2: {}".format(a.is_signed_v2()))
  File "/home/vagrant/androguard/androguard/core/bytecodes/apk.py", line 1091, in is_signed_v2
    assert size_of_block_start == size_of_block, "Sizes at beginning and and does not match!"
AssertionError: Sizes at beginning and and does not match!
```

I saw that error comming :D 

these apks are gold! We should definitely include them as tests

**Comment by eighthave** [comment]
Take note that some of them are unsigned for testing the signing
process.  They don't seem to be well marked which is which, but you can
see what they are used for by reading the Java code in src/test/

**Comment by reox** [comment]
yes - writing the testcases seems to be the problem here, as we probably want to check that the right thing is returned or an error is thrown

**Comment by reox** [comment]
I just tested the APKs in the folder and it looks like there are 18 different signing keys used but there are only 12 `.x509.pem` files... the question is now if this is an error in our code or if there are files that are signed with another key...

**Comment by reox** [comment]
it looks like I found a bug here... when reading the DER from the file and computing the hash over it, it has not the same result as using the fingerprint function from Certificate... But they should be exactly the same as the fingerprint is calculated over the DER... It looks like this is the case only for certain certificates though. That might explain the differences in hashes.

**Comment by reox** [comment]
mhh it was a bug caused by pyasn 0.3.4... Let's see what travis says.

**Comment by eighthave** [comment]
Here's a script I whipped up to check which of the test APKs have a valid signature.  _jarsigner_ alone is not enough, since it treats unsigned APKs as valid.  _apksigner_ does not, its in Debian.
```bash
$ for f in *.apk; do apksigner verify $f > /dev/null 2>&1 &&  jarsigner -verify $f > /dev/null && echo $f; donegolden-aligned-out.apk
golden-aligned-v1-out.apk
golden-aligned-v1v2-out.apk
golden-legacy-aligned-out.apk
golden-legacy-aligned-v1-out.apk
golden-legacy-aligned-v1v2-out.apk
golden-rsa-minSdkVersion-18-out.apk
golden-rsa-minSdkVersion-1-out.apk
golden-rsa-minSdkVersion-24-out.apk
golden-rsa-out.apk
golden-unaligned-out.apk
golden-unaligned-v1-out.apk
golden-unaligned-v1v2-out.apk
original.apk
targetSandboxVersion-2.apk
two-signers.apk
v1-only-max-sized-eocd-comment.apk
v1-only-pkcs7-cert-bag-first-cert-not-used.apk
v1-only-targetSandboxVersion-2.apk
v1-only-two-signers.apk
v1-only-with-dsa-sha1-1.2.840.10040.4.1-1024.apk
v1-only-with-dsa-sha1-1.2.840.10040.4.1-2048.apk
v1-only-with-dsa-sha1-1.2.840.10040.4.1-3072.apk
v1-only-with-dsa-sha1-1.2.840.10040.4.3-1024.apk
v1-only-with-dsa-sha1-1.2.840.10040.4.3-2048.apk
v1-only-with-dsa-sha1-1.2.840.10040.4.3-3072.apk
v1-only-with-dsa-sha224-1.2.840.10040.4.1-1024.apk
v1-only-with-dsa-sha224-1.2.840.10040.4.1-2048.apk
v1-only-with-dsa-sha224-1.2.840.10040.4.1-3072.apk
v1-only-with-dsa-sha224-2.16.840.1.101.3.4.3.1-1024.apk
v1-only-with-dsa-sha224-2.16.840.1.101.3.4.3.1-2048.apk
v1-only-with-dsa-sha224-2.16.840.1.101.3.4.3.1-3072.apk
v1-only-with-dsa-sha256-1.2.840.10040.4.1-1024.apk
v1-only-with-dsa-sha256-1.2.840.10040.4.1-2048.apk
v1-only-with-dsa-sha256-1.2.840.10040.4.1-3072.apk
v1-only-with-dsa-sha256-2.16.840.1.101.3.4.3.2-1024.apk
v1-only-with-dsa-sha256-2.16.840.1.101.3.4.3.2-2048.apk
v1-only-with-dsa-sha256-2.16.840.1.101.3.4.3.2-3072.apk
v1-only-with-ecdsa-sha1-1.2.840.10045.2.1-p256.apk
v1-only-with-ecdsa-sha1-1.2.840.10045.2.1-p384.apk
v1-only-with-ecdsa-sha1-1.2.840.10045.2.1-p521.apk
v1-only-with-ecdsa-sha1-1.2.840.10045.4.1-p256.apk
v1-only-with-ecdsa-sha1-1.2.840.10045.4.1-p384.apk
v1-only-with-ecdsa-sha1-1.2.840.10045.4.1-p521.apk
v1-only-with-ecdsa-sha224-1.2.840.10045.2.1-p256.apk
v1-only-with-ecdsa-sha224-1.2.840.10045.2.1-p384.apk
v1-only-with-ecdsa-sha224-1.2.840.10045.2.1-p521.apk
v1-only-with-ecdsa-sha224-1.2.840.10045.4.3.1-p256.apk
v1-only-with-ecdsa-sha224-1.2.840.10045.4.3.1-p384.apk
v1-only-with-ecdsa-sha224-1.2.840.10045.4.3.1-p521.apk
v1-only-with-ecdsa-sha256-1.2.840.10045.2.1-p256.apk
v1-only-with-ecdsa-sha256-1.2.840.10045.2.1-p384.apk
v1-only-with-ecdsa-sha256-1.2.840.10045.2.1-p521.apk
v1-only-with-ecdsa-sha256-1.2.840.10045.4.3.2-p256.apk
v1-only-with-ecdsa-sha256-1.2.840.10045.4.3.2-p384.apk
v1-only-with-ecdsa-sha256-1.2.840.10045.4.3.2-p521.apk
v1-only-with-ecdsa-sha384-1.2.840.10045.2.1-p256.apk
v1-only-with-ecdsa-sha384-1.2.840.10045.2.1-p384.apk
v1-only-with-ecdsa-sha384-1.2.840.10045.2.1-p521.apk
v1-only-with-ecdsa-sha384-1.2.840.10045.4.3.3-p256.apk
v1-only-with-ecdsa-sha384-1.2.840.10045.4.3.3-p384.apk
v1-only-with-ecdsa-sha384-1.2.840.10045.4.3.3-p521.apk
v1-only-with-ecdsa-sha512-1.2.840.10045.2.1-p256.apk
v1-only-with-ecdsa-sha512-1.2.840.10045.2.1-p384.apk
v1-only-with-ecdsa-sha512-1.2.840.10045.2.1-p521.apk
v1-only-with-ecdsa-sha512-1.2.840.10045.4.3.4-p256.apk
v1-only-with-ecdsa-sha512-1.2.840.10045.4.3.4-p384.apk
v1-only-with-ecdsa-sha512-1.2.840.10045.4.3.4-p521.apk
v1-only-with-nul-in-entry-name.apk
v1-only-with-rsa-1024.apk
v1-only-with-rsa-1024-cert-not-der2.apk
v1-only-with-rsa-pkcs1-sha1-1.2.840.113549.1.1.1-1024.apk
v1-only-with-rsa-pkcs1-sha1-1.2.840.113549.1.1.1-16384.apk
v1-only-with-rsa-pkcs1-sha1-1.2.840.113549.1.1.1-2048.apk
v1-only-with-rsa-pkcs1-sha1-1.2.840.113549.1.1.1-3072.apk
v1-only-with-rsa-pkcs1-sha1-1.2.840.113549.1.1.1-4096.apk
v1-only-with-rsa-pkcs1-sha1-1.2.840.113549.1.1.1-8192.apk
v1-only-with-rsa-pkcs1-sha1-1.2.840.113549.1.1.5-1024.apk
v1-only-with-rsa-pkcs1-sha1-1.2.840.113549.1.1.5-16384.apk
v1-only-with-rsa-pkcs1-sha1-1.2.840.113549.1.1.5-2048.apk
v1-only-with-rsa-pkcs1-sha1-1.2.840.113549.1.1.5-3072.apk
v1-only-with-rsa-pkcs1-sha1-1.2.840.113549.1.1.5-4096.apk
v1-only-with-rsa-pkcs1-sha1-1.2.840.113549.1.1.5-8192.apk
v1-only-with-rsa-pkcs1-sha224-1.2.840.113549.1.1.1-1024.apk
v1-only-with-rsa-pkcs1-sha224-1.2.840.113549.1.1.1-16384.apk
v1-only-with-rsa-pkcs1-sha224-1.2.840.113549.1.1.1-2048.apk
v1-only-with-rsa-pkcs1-sha224-1.2.840.113549.1.1.1-3072.apk
v1-only-with-rsa-pkcs1-sha224-1.2.840.113549.1.1.1-4096.apk
v1-only-with-rsa-pkcs1-sha224-1.2.840.113549.1.1.14-1024.apk
v1-only-with-rsa-pkcs1-sha224-1.2.840.113549.1.1.14-16384.apk
v1-only-with-rsa-pkcs1-sha224-1.2.840.113549.1.1.14-2048.apk
v1-only-with-rsa-pkcs1-sha224-1.2.840.113549.1.1.14-3072.apk
v1-only-with-rsa-pkcs1-sha224-1.2.840.113549.1.1.14-4096.apk
v1-only-with-rsa-pkcs1-sha224-1.2.840.113549.1.1.14-8192.apk
v1-only-with-rsa-pkcs1-sha224-1.2.840.113549.1.1.1-8192.apk
v1-only-with-rsa-pkcs1-sha256-1.2.840.113549.1.1.1-1024.apk
v1-only-with-rsa-pkcs1-sha256-1.2.840.113549.1.1.11-1024.apk
v1-only-with-rsa-pkcs1-sha256-1.2.840.113549.1.1.11-16384.apk
v1-only-with-rsa-pkcs1-sha256-1.2.840.113549.1.1.11-2048.apk
v1-only-with-rsa-pkcs1-sha256-1.2.840.113549.1.1.11-3072.apk
v1-only-with-rsa-pkcs1-sha256-1.2.840.113549.1.1.11-4096.apk
v1-only-with-rsa-pkcs1-sha256-1.2.840.113549.1.1.1-16384.apk
v1-only-with-rsa-pkcs1-sha256-1.2.840.113549.1.1.11-8192.apk
v1-only-with-rsa-pkcs1-sha256-1.2.840.113549.1.1.1-2048.apk
v1-only-with-rsa-pkcs1-sha256-1.2.840.113549.1.1.1-3072.apk
v1-only-with-rsa-pkcs1-sha256-1.2.840.113549.1.1.1-4096.apk
v1-only-with-rsa-pkcs1-sha256-1.2.840.113549.1.1.1-8192.apk
v1-only-with-rsa-pkcs1-sha384-1.2.840.113549.1.1.1-1024.apk
v1-only-with-rsa-pkcs1-sha384-1.2.840.113549.1.1.1-16384.apk
v1-only-with-rsa-pkcs1-sha384-1.2.840.113549.1.1.1-2048.apk
v1-only-with-rsa-pkcs1-sha384-1.2.840.113549.1.1.12-1024.apk
v1-only-with-rsa-pkcs1-sha384-1.2.840.113549.1.1.12-16384.apk
v1-only-with-rsa-pkcs1-sha384-1.2.840.113549.1.1.12-2048.apk
v1-only-with-rsa-pkcs1-sha384-1.2.840.113549.1.1.12-3072.apk
v1-only-with-rsa-pkcs1-sha384-1.2.840.113549.1.1.12-4096.apk
v1-only-with-rsa-pkcs1-sha384-1.2.840.113549.1.1.12-8192.apk
v1-only-with-rsa-pkcs1-sha384-1.2.840.113549.1.1.1-3072.apk
v1-only-with-rsa-pkcs1-sha384-1.2.840.113549.1.1.1-4096.apk
v1-only-with-rsa-pkcs1-sha384-1.2.840.113549.1.1.1-8192.apk
v1-only-with-rsa-pkcs1-sha512-1.2.840.113549.1.1.1-1024.apk
v1-only-with-rsa-pkcs1-sha512-1.2.840.113549.1.1.1-16384.apk
v1-only-with-rsa-pkcs1-sha512-1.2.840.113549.1.1.1-2048.apk
v1-only-with-rsa-pkcs1-sha512-1.2.840.113549.1.1.1-3072.apk
v1-only-with-rsa-pkcs1-sha512-1.2.840.113549.1.1.13-1024.apk
v1-only-with-rsa-pkcs1-sha512-1.2.840.113549.1.1.13-16384.apk
v1-only-with-rsa-pkcs1-sha512-1.2.840.113549.1.1.13-2048.apk
v1-only-with-rsa-pkcs1-sha512-1.2.840.113549.1.1.13-3072.apk
v1-only-with-rsa-pkcs1-sha512-1.2.840.113549.1.1.13-4096.apk
v1-only-with-rsa-pkcs1-sha512-1.2.840.113549.1.1.13-8192.apk
v1-only-with-rsa-pkcs1-sha512-1.2.840.113549.1.1.1-4096.apk
v1-only-with-rsa-pkcs1-sha512-1.2.840.113549.1.1.1-8192.apk
v1-only-with-signed-attrs.apk
v1-only-with-signed-attrs-signerInfo1-good-signerInfo2-good.apk
v1-only-with-signed-attrs-signerInfo1-wrong-order-signerInfo2-good.apk
v1-only-with-signed-attrs-wrong-order.apk
v1-with-apk-sig-block-but-without-apk-sig-scheme-v2-block.apk
v2-only-targetSandboxVersion-3.apk
```

**Comment by reox** [comment]
okay so on the other hand, these will not validate. But this does not tell us anything about the fact that we can extract the certificate... Maybe the certificates I see extra are caused by this? I'll check that...
```
empty-unsigned.apk                                                                                            
golden-aligned-in.apk                                                                                         
golden-aligned-v2-out.apk                                                                                     
golden-legacy-aligned-in.apk                                                                                  
golden-legacy-aligned-v2-out.apk                                                                              
golden-unaligned-in.apk                                                                                       
golden-unaligned-v2-out.apk                                                                                   
mismatched-compression-method.apk                                                                             
two-signers-second-signer-v2-broken.apk                                                                       
unsigned-targetSandboxVersion-2.apk                                                                           
v1-only-empty.apk                                                                                             
v1-only-with-cr-in-entry-name.apk                                                                             
v1-only-with-dsa-sha384-2.16.840.1.101.3.4.3.3-1024.apk                                                       
v1-only-with-dsa-sha384-2.16.840.1.101.3.4.3.3-2048.apk                                                       
v1-only-with-dsa-sha384-2.16.840.1.101.3.4.3.3-3072.apk                                                       
v1-only-with-dsa-sha512-2.16.840.1.101.3.4.3.4-1024.apk                                                       
v1-only-with-dsa-sha512-2.16.840.1.101.3.4.3.4-2048.apk                                                       
v1-only-with-dsa-sha512-2.16.840.1.101.3.4.3.4-3072.apk                                                       
v1-only-with-lf-in-entry-name.apk                                                                             
v1-only-with-rsa-1024-cert-not-der.apk                                                                        
v1-only-with-rsa-pkcs1-md5-1.2.840.113549.1.1.1-1024.apk                                                      
v1-only-with-rsa-pkcs1-md5-1.2.840.113549.1.1.1-16384.apk                                                     
v1-only-with-rsa-pkcs1-md5-1.2.840.113549.1.1.1-2048.apk                                                      
v1-only-with-rsa-pkcs1-md5-1.2.840.113549.1.1.1-3072.apk                                                      
v1-only-with-rsa-pkcs1-md5-1.2.840.113549.1.1.1-4096.apk                                                      
v1-only-with-rsa-pkcs1-md5-1.2.840.113549.1.1.1-8192.apk                                                      
v1-only-with-rsa-pkcs1-md5-1.2.840.113549.1.1.4-1024.apk                                                      
v1-only-with-rsa-pkcs1-md5-1.2.840.113549.1.1.4-16384.apk                                                     
v1-only-with-rsa-pkcs1-md5-1.2.840.113549.1.1.4-2048.apk                                                      
v1-only-with-rsa-pkcs1-md5-1.2.840.113549.1.1.4-3072.apk                                                      
v1-only-with-rsa-pkcs1-md5-1.2.840.113549.1.1.4-4096.apk                                                      
v1-only-with-rsa-pkcs1-md5-1.2.840.113549.1.1.4-8192.apk                                                      
v1-only-with-signed-attrs-missing-content-type.apk                                                            
v1-only-with-signed-attrs-missing-digest.apk                                                                  
v1-only-with-signed-attrs-multiple-good-digests.apk                                                           
v1-only-with-signed-attrs-signerInfo1-missing-content-type-signerInfo2-good.apk                               
v1-only-with-signed-attrs-signerInfo1-missing-digest-signerInfo2-good.apk                                     
v1-only-with-signed-attrs-signerInfo1-multiple-good-digests-signerInfo2-good.apk                              
v1-only-with-signed-attrs-signerInfo1-wrong-content-type-signerInfo2-good.apk                                 
v1-only-with-signed-attrs-signerInfo1-wrong-digest-signerInfo2-good.apk                                       
v1-only-with-signed-attrs-signerInfo1-wrong-signature-signerInfo2-good.apk                                    
v1-only-with-signed-attrs-wrong-content-type.apk                                                              
v1-only-with-signed-attrs-wrong-digest.apk                                                                    
v1-only-with-signed-attrs-wrong-signature.apk                                                                 
v1-sha1-sha256-manifest-and-sf.apk                                                                            
v1-sha1-sha256-manifest-and-sf-with-sha1-wrong-in-manifest.apk                                                
v1-sha1-sha256-manifest-and-sf-with-sha1-wrong-in-sf.apk                                                      
v1-sha1-sha256-manifest-and-sf-with-sha256-wrong-in-manifest.apk                                              
v1-sha1-sha256-manifest-and-sf-with-sha256-wrong-in-sf.apk                                                    
v1-sha1-sha256-manifest-and-sha1-sf.apk                                                                       
v2-only-apk-sig-block-size-mismatch.apk                                                                       
v2-only-cert-and-public-key-mismatch.apk                                                                      
v2-only-empty.apk                                                                                             
v2-only-garbage-between-cd-and-eocd.apk                                                                       
v2-only-max-sized-eocd-comment.apk                                                                            
v2-only-missing-classes.dex.apk                                                                               
v2-only-no-certs-in-sig.apk                                                                                   
v2-only-signatures-and-digests-block-mismatch.apk                                                             
v2-only-targetSandboxVersion-2.apk                                                                            
v2-only-truncated-cd.apk                                                                                      
v2-only-two-signers.apk                                                                                       
v2-only-two-signers-second-signer-no-sig.apk                                                                  
v2-only-two-signers-second-signer-no-supported-sig.apk                                                        
v2-only-unknown-pair-in-apk-sig-block.apk                                                                     
v2-only-with-dsa-sha256-1024.apk                                                                              
v2-only-with-dsa-sha256-1024-sig-does-not-verify.apk                                                          
v2-only-with-dsa-sha256-2048.apk                                                                              
v2-only-with-dsa-sha256-3072.apk                                                                              
v2-only-with-ecdsa-sha256-p256.apk                                                                            
v2-only-with-ecdsa-sha256-p256-digest-mismatch.apk                                                            
v2-only-with-ecdsa-sha256-p256-sig-does-not-verify.apk                                                        
v2-only-with-ecdsa-sha256-p384.apk                                                                            
v2-only-with-ecdsa-sha256-p521.apk                                                                            
v2-only-with-ecdsa-sha512-p256.apk                                                                            
v2-only-with-ecdsa-sha512-p384.apk                                                                            
v2-only-with-ecdsa-sha512-p521.apk                                                                            
v2-only-with-ignorable-unsupported-sig-algs.apk                                                               
v2-only-with-rsa-pkcs1-sha256-1024.apk                                                                        
v2-only-with-rsa-pkcs1-sha256-1024-cert-not-der.apk                                                           
v2-only-with-rsa-pkcs1-sha256-16384.apk                                                                       
v2-only-with-rsa-pkcs1-sha256-2048.apk                                                                        
v2-only-with-rsa-pkcs1-sha256-2048-sig-does-not-verify.apk                                                    
v2-only-with-rsa-pkcs1-sha256-3072.apk                                                                        
v2-only-with-rsa-pkcs1-sha256-4096.apk                                                                        
v2-only-with-rsa-pkcs1-sha256-8192.apk                                                                        
v2-only-with-rsa-pkcs1-sha512-1024.apk                                                                        
v2-only-with-rsa-pkcs1-sha512-16384.apk                                                                       
v2-only-with-rsa-pkcs1-sha512-2048.apk                                                                        
v2-only-with-rsa-pkcs1-sha512-3072.apk                                                                        
v2-only-with-rsa-pkcs1-sha512-4096.apk                                                                        
v2-only-with-rsa-pkcs1-sha512-4096-digest-mismatch.apk                                                        
v2-only-with-rsa-pkcs1-sha512-8192.apk                                                                        
v2-only-with-rsa-pss-sha256-1024.apk                                                                          
v2-only-with-rsa-pss-sha256-16384.apk                                                                         
v2-only-with-rsa-pss-sha256-2048.apk                                                                          
v2-only-with-rsa-pss-sha256-2048-sig-does-not-verify.apk                                                      
v2-only-with-rsa-pss-sha256-3072.apk                                                                          
v2-only-with-rsa-pss-sha256-4096.apk                                                                          
v2-only-with-rsa-pss-sha256-8192.apk                                                                          
v2-only-with-rsa-pss-sha512-16384.apk                                                                         
v2-only-with-rsa-pss-sha512-2048.apk                                                                          
v2-only-with-rsa-pss-sha512-3072.apk                                                                          
v2-only-with-rsa-pss-sha512-4096.apk                                                                          
v2-only-with-rsa-pss-sha512-8192.apk                                                                          
v2-only-wrong-apk-sig-block-magic.apk                                                                         
v2-stripped.apk                                                                                               
v2-stripped-with-ignorable-signing-schemes.apk                                                                
weird-compression-method.apk                                                                                  
```

**Comment by reox** [comment]
Okay, this is a valuable information: We are able to parse some of the broken APKs and therefore produce faulty fingerprints... I excluded them from the tests currently but probably we should investigate a little bit more.
For the other files: they might be signed correctly will not validate because of such reasons:
```
apksigner verify --verbose v2-only-with-rsa-pkcs1-sha512-8192.apk
DOES NOT VERIFY
ERROR: Missing META-INF/MANIFEST.MF
```

**Comment by eighthave** [comment]
A JAR signature without META-INF/MANIFEST.MF will never be valid.  A JAR
signature needs the three files in META-INF/ to be valid.

**Comment by reox** [comment]
verification is a different topic, but does not depend on v2 only. As v2 certificate parsing is now working, I'm closing this issue
