### ISSUE TITLE
androarsc on py2.7 has Unicode issues

### ISSUE THREAD

**Issue by reox** [androguard/androguard#446]
See:
```
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.14/bin/androarsc.py", line 113, in <module>
    main(options, arguments)
  File "/home/travis/virtualenv/python2.7.14/bin/androarsc.py", line 91, in main
    locale)).toprettyxml()
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/androguard/core/bytecodes/axml.py", line 1121, in get_string_resources
    self._analyse()
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/androguard/core/bytecodes/axml.py", line 991, in _analyse
    locale = "{}-r{}".format(language, region)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xa4' in position 0: ordinal not in range(128)
```
happens for ./examples/tests/com.example.android.wearable.wear.weardrawers.apk

```
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.14/bin/androarsc.py", line 113, in <module>
    main(options, arguments)
  File "/home/travis/virtualenv/python2.7.14/bin/androarsc.py", line 98, in main
    print(buff)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2026' in position 1493: ordinal not in range(128)
```
happens for ./examples/android/abcore/app-prod-debug.apk

Copied from the travis log: https://travis-ci.org/androguard/androguard/jobs/354005866

**Comment by reox** [comment]
This is really interesting... while this fails:
```
python2 ./androarsc.py -i $f -t string > /dev/null
Traceback (most recent call last):
  File "./androarsc.py", line 113, in <module>
    main(options, arguments)
  File "./androarsc.py", line 98, in main
    print(buff)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2026' in position 1493: ordinal not in range(128)
```

this fails not:
```
python2 ./androarsc.py -i $f -t string
```
