### ISSUE TITLE
Status of networkx and pygments dependencies

### ISSUE THREAD

**Issue by Nikoli** [androguard/androguard#48]
Since commit d4770c4b4b1cc42fbe118d0e543ae33abdf27fba CHANGELOG has `- remove useless dependencies (networkx, pygments` line, but these dependencies are still used and required.

apkviewer.py does not work if networkx is not installed:

```
$ apkviewer.py --help
Traceback (most recent call last):
  File "/usr/lib/python-exec/python2.7/apkviewer.py", line 25, in <module>
    from androguard.core.data import data
  File "/usr/lib64/python2.7/site-packages/androguard/core/data/data.py", line 18, in <module>
    from networkx import DiGraph
ImportError: No module named networkx
```

```
$ grep -e networkx -e DiGraph -c androguard/core/analysis/ganalysis.py androguard/core/data/data.py
androguard/core/analysis/ganalysis.py:85
androguard/core/data/data.py:2
```

androdd.py still tries to open pygments python module (checked via strace)

```
$ grep -i pygments -c androguard/decompiler/decompiler.py
15
```

**Comment by priscila225** [comment]
Still reproducible on latest

**Comment by reox** [comment]
as the dependencies are defined now, I'll close this one.
