### ISSUE TITLE
androgui

### ISSUE THREAD

**Issue by reox** [androguard/androguard#484]
It looks like androgui has a lot of problems - Every APK I put in gives me an error... But no exact error message is shown.

TODO:
* [ ] add error messages
* [ ] show that the GUI does something when analysing stuff
* [ ] DisamView does not resize on window change
* [ ] DisamView overwrites chars in the next line if line break is required
* [ ] binary/hex view does not allow scrolling
* [ ] what is with the plugin system?
* [ ] Be able to show the AndroidManifest.xml
* [ ] Use decompiler to print classes
* [ ] ...

**Comment by eighthave** [comment]
Also, with no APKs, it crashes:
* https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=897146
* https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=897147

**Comment by reox** [comment]
not only that! the gui is totally broken ... and it wasn't me :P

**Comment by reox** [comment]
yet another crash:
```
Traceback (most recent call last):
  File "/home/reox/git/androguard/androguard/gui/treewindow.py", line 86, in itemDoubleClickedHandler
    self.mainwin.openBinWindow(current_class)
  File "/home/reox/git/androguard/androguard/gui/mainwindow.py", line 357, in openBinWindow
    bin_window = binWidget(self, DexClassModel(current_class, dx), current_class.get_name())
  File "/home/reox/git/androguard/androguard/gui/binwindow.py", line 218, in __init__
    v = view_mode(self.themes, self.size().width(), self.size().height(), self.dataModel, self.cursor, self)
  File "/home/reox/git/androguard/androguard/gui/DisasmViewMode.py", line 226, in __init__
    self.resize(width, height)
  File "/home/reox/git/androguard/androguard/gui/DisasmViewMode.py", line 267, in resize
    self.FeedOpcodes(self.ROWS)
  File "/home/reox/git/androguard/androguard/gui/DisasmViewMode.py", line 246, in FeedOpcodes
    ins.Load()
  File "/home/reox/git/androguard/androguard/gui/DisasmViewMode.py", line 36, in Load
    H = self.get_hex().split(' ')
  File "/home/reox/git/androguard/androguard/gui/DisasmViewMode.py", line 83, in get_hex
    return self.ins.get_hex()
  File "/home/reox/git/androguard/androguard/core/bytecodes/dvm.py", line 4556, in get_hex
    return " ".join(s[i:i + 2] for i in range(0, len(s), 2))
TypeError: sequence item 0: expected str instance, bytes found
```

**Comment by eighthave** [comment]
excellent!  I think we can wait until 3.3.3 is included in buster, then
do a final fixup 3.3.4 release to include in Debian.  Seems likely we'll
find other bugs to fix in the next month before the hard freeze.
