### ISSUE TITLE
androxgmml.py: options '-e' and '-f' are broken

### ISSUE THREAD

**Issue by Nikoli** [androguard/androguard#51]
androxgmml.py works fine only if none of '-e' and '-f' options are used:
```
$ androxgmml.py -i /tmp/Torch.apk -o /tmp/androxgmml_Torch_t1.xgmml
```

```
$ androxgmml.py -i /tmp/Torch.apk -o /tmp/androxgmml_Torch_t2.xgmml -e
Traceback (most recent call last):
  File "/usr/lib/python-exec/python2.7/androxgmml.py", line 274, in <module>
    main(options, arguments)
  File "/usr/lib/python-exec/python2.7/androxgmml.py", line 262, in main
    export_apps_to_xgmml( options.input, options.output, options.functions, options.externals )
  File "/usr/lib/python-exec/python2.7/androxgmml.py", line 256, in export_apps_to_xgmml
    export_xgmml_efcg(vm, x, fd)
  File "/usr/lib/python-exec/python2.7/androxgmml.py", line 191, in export_xgmml_efcg
    if j.get_method().get_class_name() in classes and m.get_info() not in classes:
AttributeError: 'PathP' object has no attribute 'get_method'
```

```
$ androxgmml.py -i /tmp/Torch.apk -o /tmp/androxgmml_Torch_t3.xgmml -f
Traceback (most recent call last):
  File "/usr/lib/python-exec/python2.7/androxgmml.py", line 274, in <module>
    main(options, arguments)
  File "/usr/lib/python-exec/python2.7/androxgmml.py", line 262, in main
    export_apps_to_xgmml( options.input, options.output, options.functions, options.externals )
  File "/usr/lib/python-exec/python2.7/androxgmml.py", line 253, in export_apps_to_xgmml
    export_xgmml_fcg(vm, x, fd)
  File "/usr/lib/python-exec/python2.7/androxgmml.py", line 153, in export_xgmml_fcg
    if j.get_method().get_class_name() in classes and m.get_info() in classes:
AttributeError: 'PathP' object has no attribute 'get_method'

```

**Comment by adesnos** [comment]
no more supported

**Comment by doxuanthanh95** [comment]
I have similar problem, please help me!
