### ISSUE TITLE
apkviewer.py: AttributeError: 'DalvikVMFormat' object has no attribute 'dotbuff'

### ISSUE THREAD

**Issue by Nikoli** [androguard/androguard#52]
```
$ apkviewer.py -i /tmp/Torch.apk -o /tmp/apkviewer_Torch_t1
...
<androguard.core.data.data.File object at 0x2b8cfcedd50>
net/cactii/flash2/FlashDevice
<androguard.core.analysis.analysis.DVMBasicBlock object at 0x2b8cfdb6d90> 1 None
Traceback (most recent call last):
  File "/usr/lib/python-exec/python2.7/apkviewer.py", line 97, in <module>
    main(options, arguments)
  File "/usr/lib/python-exec/python2.7/apkviewer.py", line 83, in main
    buff = dd.export_dex_to_gml()
  File "/usr/lib64/python2.7/site-packages/androguard/core/data/data.py", line 101, in export_dex_to_gml
    return self.dex_data.export_to_gml()
  File "/usr/lib64/python2.7/site-packages/androguard/core/data/data.py", line 242, in export_to_gml
    buff_nodes += self.add_node( i, id_i )
  File "/usr/lib64/python2.7/site-packages/androguard/core/data/data.py", line 166, in add_node
    c_label = "%x %s\n" % (idx, self.vm.dotbuff(ins, idx))
AttributeError: 'DalvikVMFormat' object has no attribute 'dotbuff'
```

**Comment by nikhilkilivayil** [comment]
Getting the same issue. please help

**Comment by em0vskangoura** [comment]
Damn this is not fixed yet? I have this too.
So I guess its specific to something. Anyone figured a workaround ?

**Comment by adesnos** [comment]
no more supported

**Comment by berfintanriverdi** [comment]
i have the same problem.Is there still no solution to this?
