### ISSUE TITLE
when get package name raise IndexError

### ISSUE THREAD

**Issue by AmazingRaise** [androguard/androguard#535]
- Androguard Version: master
- Python Version: 2.7
- Operating System: macos

def _get_apk_package(apkname):
    try:
        a = apk.APK(apkname)
        if a.is_valid_APK():
            package_name = a.get_package().encode('ascii', 'ignore')
            return package_name
        else:
            return ''
    except Exception as e:
        traceback.print_exc()
        print '_get_apk_package error: %s' % e
        return ''
print _get_apk_package(apk_path)

Traceback (most recent call last):
  File "/Users/ZMZ/work/uusense/08-testx/testx/test/test_apk_package.py", line 36, in _get_apk_package
    a = apk.APK(apkname)
  File "/Users/ZMZ/work/uusense/08-testx/testx/androguard/core/bytecodes/apk.py", line 126, in __init__
    self._apk_analysis()
  File "/Users/ZMZ/work/uusense/08-testx/testx/androguard/core/bytecodes/apk.py", line 142, in _apk_analysis
    self.axml[i] = AXMLPrinter(manifest_data)
  File "/Users/ZMZ/work/uusense/08-testx/testx/androguard/core/bytecodes/axml.py", line 690, in __init__
    name = self.axml.getAttributeName(i)
  File "/Users/ZMZ/work/uusense/08-testx/testx/androguard/core/bytecodes/axml.py", line 537, in getAttributeName
    attr = self.m_resourceIDs[name]
IndexError: list index out of range

However, aapt works well。

**Comment by reox** [comment]
Can you upload the APK here?

**Comment by reox** [comment]
@AmazingRaise can you please test with the latest master? I merged some changes to the AXML parser, maybe this was the problem here too.
