### ISSUE TITLE
Session error

### ISSUE THREAD

**Issue by gulizseray** [androguard/androguard#552]
I'm trying to use sessions in Androguard; however, I get an error like the following. Why could this be?

Traceback (most recent call last):
  File "/Users/sanane/.virtualenvs/venv-androguard/bin/androcg_guliz.py", line 156, in <module>
    main(sess)
  File "/Users/sanane/.virtualenvs/venv-androguard/bin/androcg_guliz.py", line 78, in main
    session.Save(sess, "androguard_session_deneme.p")
  File "/Users/sanane/.virtualenvs/venv-androguard/lib/python3.7/site-packages/androguard/session.py", line 27, in Save
    pickle.dump(session, fd)
RecursionError: maximum recursion depth exceeded while pickling an object

### System Information
- Androguard Version: 3.2.0
- Python Version: 3.7.0
- Operating System: Mac OSX

**Comment by gulizseray** [comment]
What's the fix?

**Comment by reox** [comment]
The quick fix is to raise the recursionlimit:

```
import sys
sys.setrecursionlimit(50000)
```

should be enough to have this before session save.
