### ISSUE TITLE
dot not found in path

### ISSUE THREAD

**Issue by SivertPL** [androguard/androguard#688]
Is this thing even usable?
pydot is installed in both python2.7 and python3 

```
~/Desktop/kroot2$ androguard decompile -o kdebug -f png -i kdebug.apk --limit "^Lcom/.*"
[INFO    ] root: Generating grammar tables from /usr/lib/python2.7/lib2to3/Grammar.txt
[INFO    ] root: Generating grammar tables from /usr/lib/python2.7/lib2to3/PatternGrammar.txt
[INFO    ] androguard.analysis: End of creating cross references (XREF)
[INFO    ] androguard.analysis: run time: 0min 14s
Dump information kdebug.apk in kdebug
Clean directory kdebug
Decompilation ... End
Dump Lcom/a/a/b; a (Ljava/net/Proxy; Lcom/a/a/v;)Lcom/a/a/t; ... png ... Traceback (most recent call last):
  File "/home/sivert/.local/bin/androguard", line 11, in <module>
    sys.exit(entry_point())
  File "/home/sivert/.local/lib/python2.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/sivert/.local/lib/python2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/sivert/.local/lib/python2.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/sivert/.local/lib/python2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/sivert/.local/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/sivert/.local/lib/python2.7/site-packages/androguard/cli/entry_points.py", line 395, in decompile
    jar, decompiler, format_)
  File "/home/sivert/.local/lib/python2.7/site-packages/androguard/cli/main.py", line 259, in export_apps_to_format
    method2format(filename + "." + form, form, None, buff)
  File "/home/sivert/.local/lib/python2.7/site-packages/androguard/core/bytecode.py", line 392, in method2format
    getattr(g, "write_" + _format.lower())(output)
  File "/home/sivert/.local/lib/python2.7/site-packages/pydot.py", line 1734, in new_method
    encoding=encoding)
  File "/home/sivert/.local/lib/python2.7/site-packages/pydot.py", line 1817, in write
    s = self.create(prog, format, encoding=encoding)
  File "/home/sivert/.local/lib/python2.7/site-packages/pydot.py", line 1922, in create
    raise OSError(*args)
OSError: [Errno 2] "dot" not found in path.

```

**Comment by reox** [comment]
Have you followed the installation instructions? https://androguard.readthedocs.io/en/latest/intro/installation.html

You need to install graphviz.
>  In order to use features which use dot, you need Graphviz installed. This is not a python dependency but a binary package! Please follow the installation instructions for GraphvizInstall.
