### ISSUE TITLE
UnicodeDecodeError in "aosp_permissions/permissions_21.json"

### ISSUE THREAD

**Issue by Load2ing** [androguard/androguard#700]
Hi. 
I found UnicodeDecodeError in a json file.
In "androguard/core/api_specific_resources/aosp_permissions/permissions_21.json", This file included byte 0xE2 in position 39020.  I think this byte was miswritten.

Here is the error log.
ㅡㅡㅡㅡㅡㅡㅡㅡㅡ
  File "D:\CODE-PYTHON\Androguard_custom\AGParser.py", line 39, in analyze
    self.ag_apk = androguard.core.bytecodes.apk.APK(self.apk_filepath)
  File "C:\Users\Andrew_Kim\Anaconda3\lib\site-packages\androguard\core\bytecodes\apk.py", line 294, in __init__
    self._apk_analysis()
  File "C:\Users\Andrew_Kim\Anaconda3\lib\site-packages\androguard\core\bytecodes\apk.py", line 370, in _apk_analysis
    "aosp_permissions", self.get_target_sdk_version())
  File "C:\Users\Andrew_Kim\Anaconda3\lib\site-packages\androguard\core\androconf.py", line 369, in load_api_specific_resource_module
    ret = loader[resource_name](api)
  File "C:\Users\Andrew_Kim\Anaconda3\lib\site-packages\androguard\core\api_specific_resources\__init__.py", line 65, in load_permissions
    return json.load(fp)[permtype]
  File "C:\Users\Andrew_Kim\Anaconda3\lib\json\__init__.py", line 296, in load
    return loads(fp.read(),
UnicodeDecodeError: 'cp949' codec can't decode byte 0xe2 in position 39020: illegal multibyte sequence
ㅡㅡㅡㅡㅡㅡㅡㅡㅡ

**Comment by reox** [comment]
The problem seems to be that your default codec is cp949, while this file should be read as UTF8:
```
> python
Python 3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 10:22:32) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> with open('androguard/core/api_specific_resources/aosp_permissions/permissions_21.json', 'r') as fp:
...     x = fp.read()  # Works
...
>>> with open('androguard/core/api_specific_resources/aosp_permissions/permissions_21.json', 'r', encoding='utf8') as fp:
...     x = fp.read()  # works too
...
>>> with open('androguard/core/api_specific_resources/aosp_permissions/permissions_21.json', 'r', encoding='cp949') as fp:
...     x = fp.read()  # fails
...
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
UnicodeDecodeError: 'cp949' codec can't decode byte 0xe2 in position 39020: illegal multibyte sequence
```

**Comment by Load2ing** [comment]
Oh I see, thank you!
