### ISSUE TITLE
Crash when decompiling

### ISSUE THREAD

**Issue by ksg97031** [androguard/androguard#712]
**Failed to decompile the classes**

- Target APK: [app-debug.apk.zip](https://github.com/androguard/androguard/files/3246838/app-debug.apk.zip)
- Androguard Version: master
- Python Version: 3.7
- Operating System: macOS

**My Code**
```python
import sys
import re
from androguard.misc import AnalyzeAPK
from androguard.core.analysis.analysis import ClassAnalysis
from androguard.decompiler.dad.decompile import DvMethod, DvClass

sources = {}
a, d, dx = AnalyzeAPK("app-debug.apk")
for idx, dvm_f in enumerate(d):
    dexname = "classes.dex"
    if idx > 0:
        dexname = "classes{:d}.dex".format(idx + 1)
    root = {}
    sources[dexname] = root
    for cls in dvm_f.get_classes():
        cls_analyze = ClassAnalysis(cls)
        if cls_analyze.is_android_api():
            continue

        head = root
        fullname = cls.get_name()
        *pkgs, cls_name = fullname[1:-1].split('/')
        if cls_name == "R" or cls_name.startswith('R$'):
            continue

        for pkg in pkgs:
            if pkg not in head:
                head[pkg] = {}
            head = head[pkg]

        try:
            dc = DvClass(cls, dx)
            dc.process()
            head[cls_name] = dc.get_source()
        except Exception as e:
            head[cls_name] = "Failed to decompile"
            print("Error: ", e)
```
### Further Log Files and Output
```
Traceback (most recent call last):
  File "decompile.py", line 31, in <module>
    head[cls_name] = cls.get_source()
  File "/usr/local/lib/python3.7/site-packages/androguard-3.4.0-py3.7.egg/androguard/core/bytecodes/dvm.py", line 3638, in get_source
    return self.CM.decompiler_ob.get_source_class(self)
  File "/usr/local/lib/python3.7/site-packages/androguard-3.4.0-py3.7.egg/androguard/decompiler/decompiler.py", line 593, in get_source_class
    return c.get_source()
  File "/usr/local/lib/python3.7/site-packages/androguard-3.4.0-py3.7.egg/androguard/decompiler/dad/decompile.py", line 320, in get_source
    value = '"%s"' % value.encode("unicode-escape").decode("ascii")
AttributeError: 'MUTF8String' object has no attribute 'encode'
```

Below code is ok for me
```python
24 from androguard.core.mutf8 import MUTF8String
...
314             if init_value:
315                 value = init_value.value
316                 if f_type == 'String':
317                     if value:
318                         if isinstance(value, MUTF8String): # new codeline
319                             value = '"%s"' % value.decode("ascii")
320                         else:
321                             value = '"%s"' % value.encode("unicode-escape").decode("ascii")
```

**Comment by reox** [comment]
@Neakxs can you maybe have a look? Maybe the .encode().decode() can be removed all together in this situation

**Comment by Neakxs** [comment]
Maybe setting `value = '"%s"' % str(value)` at https://github.com/androguard/androguard/blob/caaec7384a7736a5c2c677477881fc01c824a5eb/androguard/decompiler/dad/decompile.py#L318 ?

**Comment by ksg97031** [comment]
@reox @Neakxs the value is always MUTF8String type in my test.

**Comment by reox** [comment]
tested with the latest master, the script works.
If you encounter any other error, please feel free to open a new ticket or reopen this one!
