### ISSUE TITLE
KeyError with "DALVIK_OPCODES_FORMAT" in "dvm.py"

### ISSUE THREAD

**Issue by Load2ing** [androguard/androguard#719]
This issue seems like the same as #149.
I'm attaching a DEX file.
DEX : [classes.dex.zip](https://github.com/androguard/androguard/files/3295865/classes.dex.zip)

- Androguard Version: 3.3.5
- Python Version: 3.6.4
- OS: Windows 10

**Source Code**
```
import androguard.core.bytecodes.dvm as advm

def main():
	fd = open("D:\\TEMP\\A1\\classes.dex", mode='rb')
	dex_b = fd.read()
	ag_vm = advm.DalvikVMFormat(buff=dex_b)
	
	class_list = ag_vm.get_classes()
	for _class_def_item in class_list:
		method_list = _class_def_item.get_methods()
		for _encoded_method in method_list:
			Dalvik_Code = _encoded_method.get_code()
			if Dalvik_Code is None:
				continue
				
			DCode = Dalvik_Code.get_bc()
			inst_list = DCode.get_instructions()
			for inst in inst_list:
				opcode = inst.get_op_value()
				
				if opcode in advm.DALVIK_OPCODES_PAYLOAD or opcode < 0:
					continue
					
				try: 				
					kind = inst.get_kind()
				except IndexError:
					continue
				
if __name__ == "__main__":
	main()
```

**Logs**
```
Traceback (most recent call last):
  File "D:\TEMP\A1\TestAndroguard.py", line 30, in <module>
    main()
  File "D:\TEMP\A1\TestAndroguard.py", line 25, in main
    kind = inst.get_kind()
  File "C:\Users\Andrew_Kim\Anaconda3\lib\site-packages\androguard\core\bytecodes\dvm.py", line 4059, in get_kind
    return DALVIK_OPCODES_FORMAT[self.OP][1][1]
KeyError: 255
```

**Comment by reox** [comment]
Can you try with the changes in PR #681 ?

**Comment by Load2ing** [comment]
I tried using #681 and there was no error. but It printed about 1000 invalid instruction messages.

**Comment by reox** [comment]
Okay, maybe there are^^ sometimes it is used as obfuscation...
Can you check with other decompilers like jadx?
I'm little bit low on time right now :(
