### ISSUE TITLE
AttributeError: 'DiGraph' object has no attribute 'node'

### ISSUE THREAD

**Issue by elig0n** [androguard/androguard#769]
C:> androguard cg some.apk

>Traceback (most recent call last):
  File "c:\python38\lib\runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python38\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python38\Scripts\androguard.exe\__main__.py", line 7, in <module>
  File "c:\python38\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "c:\python38\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "c:\python38\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\python38\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\python38\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\python38\lib\site-packages\androguard\cli\entry_points.py", line 319, in cg
    androcg_main(verbose=verbose,
  File "c:\python38\lib\site-packages\androguard\cli\main.py", line 105, in androcg_main
    CG = dx.get_call_graph(classname,
  File "c:\python38\lib\site-packages\androguard\core\analysis\analysis.py", line 1432, in get_call_graph
    _add_node(CG, orig_method, entry_points)
  File "c:\python38\lib\site-packages\androguard\core\analysis\analysis.py", line 1406, in _add_node
    if method not in G.node:
AttributeError: 'DiGraph' object has no attribute 'node'

androguard, version 3.3.5
Python 3.8.0
Windows 10
dot - graphviz version 2.38.0 (20140413.2041)

**Comment by sandrotosi** [comment]
JFYI, this is preventing the package to be included in the upcoming Debian stable release, a fix would be highly appreciated. thanks! :)

**Comment by sandrotosi** [comment]
https://ci.debian.net/data/autopkgtest/testing/amd64/a/androguard/3495118/log.gz

**Comment by sandrotosi** [comment]
```
--- a/androguard/core/analysis/analysis.py
+++ b/androguard/core/analysis/analysis.py
@@ -1403,7 +1403,7 @@ class Analysis:
             """
             Wrapper to add methods to a graph
             """
-            if method not in G.node:
+            if method not in G.nodes:
                 if isinstance(method, ExternalMethod):
                     is_external = True
                 else:
```

this ensures compatibility with networkx 2.4

**Comment by reox** [comment]
hmm I remembering changing this back and forth, because networkx changed a few things there as well. Yes, G.nodes seems to be the current syntax.

**Comment by elig0n** [comment]
@reox The master works alright for me.

**Comment by Kushagra2000** [comment]
I have the exact same issue on androguard 3.3.5 installed via pip on Pop!OS. Can somebody clarify in detail on how to fix this error?
Python version 3.8.6
graphviz version 2.42.2-4

**Comment by amoghbl1** [comment]
Installing the master branch instead of the 3.3.5 release works fine @Kushagra2000
