### ISSUE TITLE
androguard improt error

### ISSUE THREAD

**Issue by geunhayou66** [androguard/androguard#808]
I want to use `androxgmml.py`
But these errors occur.

> Traceback (most recent call last):
  File "androguard-master/androxgmml.py", line 25, in <module>
    from androguard.core.androgen import Androguard
  File "/home/hbryu66/Desktop/AndrODet/androguard-master/androguard/core/androgen.py", line 18, in <module>
    from androguard.core import androconf
  File "/home/hbryu66/Desktop/AndrODet/androguard-master/androguard/core/androconf.py", line 175
    raise ValueError, 'the input must be an integer'
                                      ^
SyntaxError: invalid syntax

My environment is as follows: 
OS : ubuntu 18.04 and 16.04
Python 3.7

Can't I use `androxgmml.py` with Python3 anymore?

Others like `androlyze.py`, `androdiff.py` and etc. occur same problem.

**Comment by AkshatSood** [comment]
@geunhayou66 did you find a solution for this?
