### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by 89z** [androguard/androguard#879]
### Describe what you wanted to do

All I want to do is dump the source code files from an APK, so if a better way is available, I am open to it.

### System Information

- Androguard Version: `androguard==3.3.5`
- Python Version: 3.9.6
- Operating System: Windows

### Further Log Files and Output

Here is the APK I used and the script, as well as full trace:

https://apkpure.com/bandcamp/com.bandcamp.android

~~~py
from androguard.core.analysis import analysis
from androguard.core.bytecodes import apk
from androguard.core.bytecodes import dvm
from androguard.decompiler.dad import decompile
from sys import argv
from sys import exit
import os

def convert_descriptor(name):
	name = name[1:]
	return name.replace("/",".").replace(";","")

def check_dirs(directory):
		if not os.path.exists(PREFIX+directory):
			try:
				os.makedirs(PREFIX+directory)	
			except:
				pass

def check_path(class_path):
		org_path = class_path.replace(".","/")
		paths = org_path.split("/")
		paths = paths[:len(paths)-1]
		for index,folder in enumerate(paths):
			check_dirs('/'.join(paths[:index+1]))	
		return PREFIX+org_path+".java"

PREFIX=argv[2]	
a = apk.APK(argv[1])
d = dvm.DalvikVMFormat(a.get_dex())
vmx = analysis.Analysis(d)
for _class in d.get_classes():
       class_path = convert_descriptor(_class.get_name())
       path = check_path(class_path)
       if not os.path.exists(path):
               java = open(path,"w")
               for field in _class.get_fields():
                       access_flags = field.get_access_flags_string()
                       if access_flags == "0x0":
                               access_flags = ""
                       java.write("\t%s %s %s\n"% (access_flags,convert_descriptor(field.get_descriptor()),field.get_name()))
               for method in _class.get_methods():
                       g = vmx.get_method(method)	
                       if method.get_code() == None:
                               continue
                       ms = decompile.DvMethod(g)
                       ms.process()
                       for line in ms.get_source().split("\n"):
                               java.write("\t%s\n" % line)
               java.flush()
               java.close()	
~~~

Result:

~~~
Multiple exit nodes found !
Traceback (most recent call last):
  File "D:\Desktop\etc\dec.py", line 58, in <module>
    ms.process()
  File "C:\python\lib\site-packages\androguard\decompiler\dad\decompile.py", line 190, in process
    self.writer.write_method()
  File "C:\python\lib\site-packages\androguard\decompiler\dad\writer.py", line 197, in write_method
    self.visit_node(self.graph.entry)
  File "C:\python\lib\site-packages\androguard\decompiler\dad\writer.py", line 213, in visit_node
    node.visit(self)
  File "C:\python\lib\site-packages\androguard\decompiler\dad\basic_blocks.py", line 161, in visit
    return visitor.visit_cond_node(self)
  File "C:\python\lib\site-packages\androguard\decompiler\dad\writer.py", line 321, in visit_cond_node
    self.visit_node(cond.true)
  File "C:\python\lib\site-packages\androguard\decompiler\dad\writer.py", line 213, in visit_node
    node.visit(self)
  File "C:\python\lib\site-packages\androguard\decompiler\dad\basic_blocks.py", line 75, in visit
    return visitor.visit_statement_node(self)
  File "C:\python\lib\site-packages\androguard\decompiler\dad\writer.py", line 392, in visit_statement_node
    self.visit_node(sucs[0])
  File "C:\python\lib\site-packages\androguard\decompiler\dad\writer.py", line 213, in visit_node
    node.visit(self)
  File "C:\python\lib\site-packages\androguard\decompiler\dad\basic_blocks.py", line 284, in visit
    visitor.visit_try_node(self)
  File "C:\python\lib\site-packages\androguard\decompiler\dad\writer.py", line 402, in visit_try_node
    self.visit_node(catch)
  File "C:\python\lib\site-packages\androguard\decompiler\dad\writer.py", line 213, in visit_node
    node.visit(self)
  File "C:\python\lib\site-packages\androguard\decompiler\dad\basic_blocks.py", line 302, in visit
    visitor.visit_catch_node(self)
  File "C:\python\lib\site-packages\androguard\decompiler\dad\writer.py", line 408, in visit_catch_node
    catch_node.visit_exception(self)
  File "C:\python\lib\site-packages\androguard\decompiler\dad\basic_blocks.py", line 308, in visit_exception
    visitor.write(get_type(self.catch_type))
  File "C:\python\lib\site-packages\androguard\decompiler\dad\util.py", line 176, in get_type
    if atype[0] == 'L':
TypeError: 'NoneType' object is not subscriptable
~~~

**Comment by 89z** [comment]
This seems to do what I am wanting:

~~~py
from androguard.misc import AnalyzeAPK
import sys

a,d,dx= AnalyzeAPK('Bandcamp_v2.4.11_apkpure.com.apk')
f = open('bc.java', 'w')

for dd in d:
   for clas in dd.get_classes():
      name = clas.get_name()
      if 'bandcamp' in name:
         print(name, file=f)
         src = dd.get_class(name).get_source()
         print(src, file=f)
~~~
