### ISSUE TITLE
'bytes' object has no attribute 'DEX'

### ISSUE THREAD

**Issue by jacopo-degattis** [androguard/androguard#905]
Hi everyone,
I just discovered and installed androguard and I'm trying to execute the "AnalyseAPK" function.

```python
from androguard.misc import AnalyzeAPK
a, d, dx = AnalyzeAPK("../x.apk")
```

When I executed the second line it throws this error

```
File ~/Downloads/androguard/androguard/misc.py:65, in AnalyzeAPK(_file, session, raw)
     63 dx = Analysis()
     64 for dex in a.get_all_dex():
---> 65     df = dex.DEX(dex, using_api=a.get_target_sdk_version())
     66     dx.add(df)
     67     d.append(df)

AttributeError: 'bytes' object has no attribute 'DEX'
```

I can't figure out what the problem could be, does anyone know what could it be ?

Thanks !

**Comment by saucer-man** [comment]
Also meet this

**Comment by SioYooo** [comment]
Run into same issue

```
2022-10-03 11:11:37.848 | INFO     | androguard.core.apk:_apk_analysis:370 - APK file was successfully validated!
2022-10-03 11:11:37.849 | DEBUG    | androguard.core.api_specific_resources:load_permissions:48 - Available API levels: 4, 5, 6, 7, 8, 9, 10, 13, 14, 15, 16, 17, 18, 19, 21, 22, 23, 24, 25, 26, 27, 28, 29
2022-10-03 11:11:37.849 | WARNING  | androguard.core.api_specific_resources:load_permissions:52 - Requested API level 31 is larger than maximum we have, returning API level 29 instead.
2022-10-03 11:11:37.849 | DEBUG    | androguard.core.api_specific_resources:load_permissions:48 - Available API levels: 4, 5, 6, 7, 8, 9, 10, 13, 14, 15, 16, 17, 18, 19, 21, 22, 23, 24, 25, 26, 27, 28, 29
2022-10-03 11:11:37.850 | DEBUG    | androguard.core.api_specific_resources:load_permissions:48 - Available API levels: 4, 5, 6, 7, 8, 9, 10, 13, 14, 15, 16, 17, 18, 19, 21, 22, 23, 24, 25, 26, 27, 28, 29
Traceback (most recent call last):
  File "/home/sioyoo/tools/BOAFuzzer/call_graph_generator.py", line 59, in <module>
    main(sys.argv)
  File "/home/sioyoo/tools/BOAFuzzer/call_graph_generator.py", line 53, in main
    get_apk_cg(apk)
  File "/home/sioyoo/tools/BOAFuzzer/call_graph_generator.py", line 15, in get_apk_cg
    a, d, dx = AnalyzeAPK("/data/sioyoo_app/vanced_manager.apk")
  File "/home/sioyoo/tools/BOAFuzzer/androguard/misc.py", line 65, in AnalyzeAPK
    df = dex.DEX(dex, using_api=a.get_target_sdk_version())
AttributeError: 'bytes' object has no attribute 'DEX'
```

**Comment by erev0s** [comment]
Given that the issue refers to a rather old version of the project and the project is substantially different nowadays, I will be closing this.
Please feel free to reopen it in case it still stands.
