### ISSUE TITLE
ModuleNotFoundError: No module named 'androguard.core.bytecodes'

### ISSUE THREAD

**Issue by Drjacky** [androguard/androguard#922]
### Describe what you wanted to do

Decompile an APK

### System Information

- Androguard Version: 3.3.5
- Python Version: 3.11.2
- Operating System: macOS

### Further Log Files and Output

```bash
.
.
.
2023-02-25 11:52:08.674 | INFO     | androguard.core.analysis.analysis:add:1435 - Adding DEX file version 37
2023-02-25 11:52:15.642 | INFO     | androguard.core.analysis.analysis:add:1458 - Added DEX in the analysis took : 0min 06s
2023-02-25 11:52:22.768 | INFO     | androguard.core.analysis.analysis:create_xref:1492 - End of creating cross references (XREF) run time: 0min 07s
2023-02-25 11:52:22.769 | INFO     | androguard.session:addAPK:160 - added APK sample.apk:c1211fdc672ac17426a311ee2c8a1d351d7514bca9d8a313e525c68d9186fbea
Traceback (most recent call last):
  File "androguard/cli.py", line 505, in <module>
    entry_point()
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "androguard/cli.py", line 317, in decompile
    export_apps_to_format(fname, s, output, limit,
  File "androguard/main.py", line 84, in export_apps_to_format
    from androguard.core.bytecodes import dvm
ModuleNotFoundError: No module named 'androguard.core.bytecodes'
```

**Comment by erev0s** [comment]
Given that the issue refers to a rather old version of the project and the project is substantially different nowadays, I will be closing this.
Please feel free to reopen it in case it still stands.

**Comment by Drjacky** [comment]
> Given that the issue refers to a rather old version of the project and the project is substantially different nowadays, I will be closing this. Please feel free to reopen it in case it still stands.

What do you mean old version of the project? ANdroguard project? I used the latest version https://github.com/androguard/androguard/releases/tag/v3.3.5

**Comment by erev0s** [comment]
@Drjacky please install latest version from PyPI
https://pypi.org/project/androguard/

**Comment by Drjacky** [comment]
Is this normal?

```bash
androguard decompile -i example.apk -o /outttt/

...
[INFO    ] androguard.analysis: run time: 0min 00s
[INFO    ] androguard.analysis: End of creating cross references (XREF)
[INFO    ] androguard.analysis: run time: 0min 00s
[INFO    ] androguard.analysis: End of creating cross references (XREF)
[INFO    ] androguard.analysis: run time: 0min 00s
[INFO    ] androguard.analysis: End of creating cross references (XREF)
[INFO    ] androguard.analysis: run time: 0min 00s
[INFO    ] androguard.analysis: End of creating cross references (XREF)
[INFO    ] androguard.analysis: run time: 0min 01s
[INFO    ] androguard.analysis: End of creating cross references (XREF)
[INFO    ] androguard.analysis: run time: 0min 01s
[INFO    ] androguard.analysis: End of creating cross references (XREF)
[INFO    ] androguard.analysis: run time: 0min 01s
[INFO    ] androguard.analysis: End of creating cross references (XREF)
.
.
.
```
it is continuing and there is no output

**Comment by Drjacky** [comment]
Okay, after waiting for a while, it printed this:
```bash
[INFO    ] androguard.analysis: run time: 0min 19s
Added file to session: SHA256::c1211fdc67........8a313e525c68d9186fbea
Loaded APK file...
>>> a
<androguard.core.bytecodes.apk.APK object at 0x1079ab410>
>>> d
[<androguard.core.bytecodes.dvm.DalvikVMFormat object at 0x115827ad0>, <androguard.core.bytecodes.dvm.DalvikVMFormat object at 0x1179f21d0>, <androguard.core.bytecodes.dvm.DalvikVMFormat object at 0x2c6225f90>, <androguard.core.bytecodes.dvm.DalvikVMFormat object at 0x3170e5210>, <androguard.core.bytecodes.dvm.DalvikVMFormat object at 0x463633910>]
>>> dx
<analysis.Analysis VMs: 54, Classes: 74000, Strings: 83000>

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
File /opt/homebrew/bin/androguard:8
      6 if __name__ == '__main__':
      7     sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
----> 8     sys.exit(entry_point())

File /opt/homebrew/lib/python3.11/site-packages/click/core.py:1157, in BaseCommand.__call__(self, *args, **kwargs)
   1155 def __call__(self, *args: t.Any, **kwargs: t.Any) -> t.Any:
   1156     """Alias for :meth:`main`."""
-> 1157     return self.main(*args, **kwargs)

File /opt/homebrew/lib/python3.11/site-packages/click/core.py:1078, in BaseCommand.main(self, args, prog_name, complete_var, standalone_mode, windows_expand_args, **extra)
   1076 try:
   1077     with self.make_context(prog_name, args, **extra) as ctx:
-> 1078         rv = self.invoke(ctx)
   1079         if not standalone_mode:
   1080             return rv

File /opt/homebrew/lib/python3.11/site-packages/click/core.py:1688, in MultiCommand.invoke(self, ctx)
   1686         sub_ctx = cmd.make_context(cmd_name, args, parent=ctx)
   1687         with sub_ctx:
-> 1688             return _process_result(sub_ctx.command.invoke(sub_ctx))
   1690 # In chain mode we create the contexts step by step, but after the
   1691 # base command has been invoked.  Because at that point we do not
   1692 # know the subcommands yet, the invoked subcommand attribute is
   1693 # set to ``*`` to inform the command that subcommands are executed
   1694 # but nothing else.
   1695 with ctx:

File /opt/homebrew/lib/python3.11/site-packages/click/core.py:1434, in Command.invoke(self, ctx)
   1431     echo(style(message, fg="red"), err=True)
   1433 if self.callback is not None:
-> 1434     return ctx.invoke(self.callback, **ctx.params)

File /opt/homebrew/lib/python3.11/site-packages/click/core.py:783, in Context.invoke(_Context__self, _Context__callback, *args, **kwargs)
    781 with augment_usage_errors(__self):
    782     with ctx:
--> 783         return __callback(*args, **kwargs)

File /opt/homebrew/lib/python3.11/site-packages/androguard/cli/entry_points.py:476, in analyze(session, apk)
    461 @entry_point.command()
    462 @click.option(
    463     '--session',
   (...)
    473 )
    474 def analyze(session, apk):
    475     """Open a IPython Shell and start reverse engineering."""
--> 476     androlyze_main(session, apk)

File /opt/homebrew/lib/python3.11/site-packages/androguard/cli/main.py:416, in androlyze_main(session, filename)
    413 ipshell = InteractiveShellEmbed(config=cfg, banner1="{} started"
    414                                 .format(_version_string))
    415 atexit.register(shutdown_hook)
--> 416 init_print_colors()
    417 ipshell()

File /opt/homebrew/lib/python3.11/site-packages/androguard/misc.py:18, in init_print_colors()
     16 from IPython.utils import coloransi, io
     17 androconf.default_colors(coloransi.TermColors)
---> 18 androconf.CONF["PRINT_FCT"] = io.stdout.write

AttributeError: module 'IPython.utils.io' has no attribute 'stdout'
Do you want to save the session? (y/[n])?y
Exception ignored in atexit callback: <function androlyze_main.<locals>.shutdown_hook at 0x1105ca3e0>
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/androguard/cli/main.py", line 408, in shutdown_hook
    fname = s.save()
            ^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/androguard/session.py", line 135, in save
    return Save(self, filename)
           ^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/androguard/session.py", line 59, in Save
    pickle.dump(session, fd)
TypeError: cannot pickle 'module' object
```

**Comment by Drjacky** [comment]
> @Drjacky please install latest version from PyPI https://pypi.org/project/androguard/

I uninstalled python@3.11 and just kept python@3.12 and now when I want to install it via pypi:
```bash
➜  ~ pip install androguard
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try brew install
    xyz, where xyz is the package you are trying to
    install.

    If you wish to install a non-brew-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip.

    If you wish to install a non-brew packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.
WARNING: Skipping /opt/homebrew/lib/python3.12/site-packages/pygments-2.17.2.dist-info due to invalid metadata entry 'name'
```

**Comment by Drjacky** [comment]
> > please install latest version from PyPI https://pypi.org/project/androguard/
> 
> I uninstalled python@3.11 and just kept python@3.12 and now when I want to install it via pypi:
> 
> ```shell
> ➜  ~ pip install androguard
> error: externally-managed-environment
> 
> × This environment is externally managed
> ╰─> To install Python packages system-wide, try brew install
>     xyz, where xyz is the package you are trying to
>     install.
> 
>     If you wish to install a non-brew-packaged Python package,
>     create a virtual environment using python3 -m venv path/to/venv.
>     Then use path/to/venv/bin/python and path/to/venv/bin/pip.
> 
>     If you wish to install a non-brew packaged Python application,
>     it may be easiest to use pipx install xyz, which will manage a
>     virtual environment for you. Make sure you have pipx installed.
> 
> note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
> hint: See PEP 668 for the detailed specification.
> WARNING: Skipping /opt/homebrew/lib/python3.12/site-packages/pygments-2.17.2.dist-info due to invalid metadata entry 'name'
> ```

I had to delete `EXTERNALLY-MANAGED` by running `rm /opt/homebrew/Cellar/python\@3*/**/EXTERNALLY-MANAGED`

**Comment by Drjacky** [comment]
Now I tried to decompile an APK (having python@3.12 installed) and I got:
```bash
2023-12-16 15:15:19.761 | INFO     | androguard.core.analysis.analysis:create_xref:1479 - End of creating cross references (XREF) run time: 0min 26s
2023-12-16 15:15:19.761 | INFO     | androguard.session:addAPK:156 - added APK example..apk:c1211fd......9d8a313e525c68d9186fbea
Dump information example.apk in /outttt/
Clean directory /outttt/
Decompilation ... End
Dump Lcom/example/labor/view/R$anim; <init> ()V ... source codes ... bytecodes ... Traceback (most recent call last):
  File "/opt/homebrew/bin/androguard", line 8, in <module>
    sys.exit(entry_point())
             ^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/androguard/cli/cli.py", line 303, in decompile
    export_apps_to_format(fname, s, output, limit,
  File "/opt/homebrew/lib/python3.12/site-packages/androguard/cli/main.py", line 173, in export_apps_to_format
    bytecode_buff = DEX.get_bytecodes_method(vm, vmx, method)
                    ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'DEX' has no attribute 'get_bytecodes_method'

```

**Comment by erev0s** [comment]
@Drjacky the rest of the errors are related to your system
the last one indeed is an issue and i can replicate it
will take a look and answer in the issue you opened
