### ISSUE TITLE
s390x: androguard.axml:This does not look like an AXML file. header size does not equal 8! header size = 8308

### ISSUE THREAD

**Issue by eighthave** [androguard/androguard#928]
### Describe what you wanted to do

Parsing APKs on Debian running on the s390x arch (big-endian) fails with errors like: "androguard.axml:This does not look like an AXML file. header size does not equal 8! header size = 8308".  I believe this is because s390x is a big-endian architecture, unlike amd64, ppc64el, etc.

### Describe what you expected

Parsing to work, like it does on other arches.

### Describe what actually happened

Debian/bookworm/amd64:
```console
$ androguard apkid SpeedoMeterApp.main_1.apk 
{
  "SpeedoMeterApp.main_1.apk": [
    "SpeedoMeterApp.main",
    "1",
    "1.0"
  ]
}
```

Debian/bookworm/s390x:
```console
$ androguard apkid SpeedoMeterApp.main_1.apk 
Traceback (most recent call last):
  File "/usr/bin/androguard", line 33, in <module>
    sys.exit(load_entry_point('androguard==3.4.0a1', 'console_scripts', 'androguard')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/androguard/cli/entry_points.py", line 443, in apkid
    results[apk] = androguard.core.bytecodes.apk.get_apkid(apk)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/androguard/core/bytecodes/apk.py", line 2202, in get_apkid
    raise RuntimeError('{path}: <manifest> must be the first element in AndroidManifest.xml'
RuntimeError: SpeedoMeterApp.main_1.apk: <manifest> must be the first element in AndroidManifest.xml
```

### System Information

- Androguard Version: 3.4.0~a1-6
- Python Version: 3.11
- Operating System:  Debian/bookworm on s390x

**Comment by eighthave** [comment]
Here's another example from the interactive Python shell:
```
>>> from androguard.core.bytecodes.apk import APK
>>> APK('tests/SpeedoMeterApp.main_1.apk')
Name '洀愀渀椀昀攀猀琀' contains invalid characters!
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/androguard/core/bytecodes/apk.py", line 291, in __init__
    self._apk_analysis()
  File "/usr/lib/python3/dist-packages/androguard/core/bytecodes/apk.py", line 315, in _apk_analysis
    ap = AXMLPrinter(manifest_data)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/androguard/core/bytecodes/axml/__init__.py", line 937, in __init__
    elem = etree.Element(tag, nsmap=self.axml.nsmap)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "src/lxml/etree.pyx", line 3042, in lxml.etree.Element
  File "src/lxml/apihelpers.pxi", line 131, in lxml.etree._makeElement
  File "src/lxml/apihelpers.pxi", line 118, in lxml.etree._makeElement
  File "src/lxml/apihelpers.pxi", line 215, in lxml.etree._setNodeNamespaces
  File "src/lxml/apihelpers.pxi", line 1775, in lxml.etree._uriValidOrRaise
ValueError: Invalid namespace URI '栀琀琀瀀㨀⼀⼀猀挀栀攀洀愀猀⸀愀渀搀爀漀椀搀⸀挀漀洀⼀愀瀀欀⼀爀攀猀⼀愀渀搀爀漀椀搀'
```
The bug seems to turn chars into Chinese.

**Comment by eighthave** [comment]
Here is the APK I used:
https://gitlab.com/fdroid/fdroidserver/-/blob/2.2.1/tests/SpeedoMeterApp.main_1.apk

But this happens with an APK I tried.  All work fine on amd64.

**Comment by erev0s** [comment]
@eighthave yes you are right, this happens because s390x is a big-endian and all the processing is done taking in mind little-endian. Its not a bad idea to adjust androguard to take this into account, but I would rate it with low priority atm at least.
