### ISSUE TITLE
I encountered an error when using this project to analyze the APK

### ISSUE THREAD

**Issue by Daikq** [androguard/androguard#937]
PS D:\desktop\androguard-master> python .\cli.py  analyze ..\ygck.pro.apk
2023-06-12 10:31:54.670 | INFO     | androguard.session:__init__:54 - Opening database <Database(sqlite:///androguard.db)>
2023-06-12 10:31:54.694 | INFO     | androguard.session:__init__:63 - Creating new session [1]
2023-06-12 10:31:54.696 | INFO     | main:androlyze_main:225 - Please be patient, this might take a while.
2023-06-12 10:31:54.708 | INFO     | main:androlyze_main:229 - Found the provided file is of type 'APK'
2023-06-12 10:31:54.732 | INFO     | androguard.session:addAPK:136 - add APK ..\ygck.pro.apk:3b56504d28d7f04c62233f70c9818092618d4a3ab651570f674d3590d2d87c4b
2023-06-12 10:31:54.759 | INFO     | androguard.core.apk:_apk_analysis:311 - Starting analysis on AndroidManifest.xml
2023-06-12 10:31:55.051 | INFO     | androguard.core.apk:_apk_analysis:368 - APK file was successfully validated!
Traceback (most recent call last):
  File "D:\desktop\androguard-master\cli.py", line 470, in <module>
    entry_point()
  File "C:\Users\Daikq\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Daikq\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\Daikq\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Daikq\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Daikq\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "D:\desktop\androguard-master\cli.py", line 378, in analyze
    androlyze_main(session, apk)
  File "D:\desktop\androguard-master\main.py", line 242, in androlyze_main
    h = s.add(filename, raw)
  File "D:\desktop\androguard-master\androguard\session.py", line 266, in add
    digest, _ = self.addAPK(filename, raw_data)
  File "D:\desktop\androguard-master\androguard\session.py", line 140, in addAPK
    newapk = apk.APK(data, True)
  File "D:\desktop\androguard-master\androguard\core\apk\__init__.py", line 293, in __init__
    self._apk_analysis()
  File "D:\desktop\androguard-master\androguard\core\apk\__init__.py", line 370, in _apk_analysis
    self.permission_module = androconf.load_api_specific_resource_module(
  File "D:\desktop\androguard-master\androguard\core\androconf.py", line 274, in load_api_specific_resource_module
    ret = loader[resource_name](api)
  File "D:\desktop\androguard-master\androguard\core\api_specific_resources\__init__.py", line 64, in load_permissions
    return json.load(fp)[permtype]
  File "C:\Users\Daikq\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Users\Daikq\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Daikq\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Daikq\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 3372 column 191 (char 123104)

### System Information

- Androguard Version: master
- Python Version: 3.10
- windows

**Comment by erev0s** [comment]
@Daikq  could you please share the apk to try it out?
