### ISSUE TITLE
androguard.core.axml.ResParserError: UTF-8 String is not null terminated! At offset=74651

### ISSUE THREAD

**Issue by guri87-byte** [androguard/androguard#941]
Getting this error when trying to get icon via `a.get_app_icon`:

```bash
Traceback (most recent call last):
  File "/home/mach/app-py/app.py", line 29, in <module>
    entry()
  File "/usr/lib/python3/dist-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/mach/app-py/app.py", line 23, in entry
    manifest_obj = manifest.Manifest(apkobj)
  File "/home/mach/app-py/manifest.py", line 15, in __init__
    self.icon_base64 = self.get_base64_icon()
  File "/home/mach/app-py/manifest.py", line 24, in get_base64_icon
    icon = self.apkobj.get_app_icon()
  File "/home/mach/app-py/androguard/androguard/core/apk/__init__.py", line 581, in get_app_icon
    candidates = res_parser.get_resolved_res_configs(res_id)
  File "/home/mach/app-py/androguard/androguard/core/axml/__init__.py", line 1985, in get_resolved_res_configs
    return resolver.resolve(rid)
  File "/home/mach/app-py/androguard/androguard/core/axml/__init__.py", line 1917, in resolve
    self._resolve_into_result(result, res_id, self.wanted_config)
  File "/home/mach/app-py/androguard/androguard/core/axml/__init__.py", line 1922, in _resolve_into_result
    configs = self.resources.get_res_configs(res_id, config)
  File "/home/mach/app-py/androguard/androguard/core/axml/__init__.py", line 2042, in get_res_configs
    self._analyse()
  File "/home/mach/app-py/androguard/androguard/core/axml/__init__.py", line 1554, in _analyse
    self.get_resource_string(ate))
  File "/home/mach/app-py/androguard/androguard/core/axml/__init__.py", line 1583, in get_resource_string
    return [ate.get_value(), ate.get_key_data()]
  File "/home/mach/app-py/androguard/androguard/core/axml/__init__.py", line 2861, in get_key_data
    return self.key.get_data_value()
  File "/home/mach/app-py/androguard/androguard/core/axml/__init__.py", line 2930, in get_data_value
    return self.parent.stringpool_main.getString(self.data)
  File "/home/mach/app-py/androguard/androguard/core/axml/__init__.py", line 210, in getString
    self._cache[idx] = self._decode8(offset)
  File "/home/mach/app-py/androguard/androguard/core/axml/__init__.py", line 244, in _decode8
    raise ResParserError("UTF-8 String is not null terminated! At offset={}".format(offset))
androguard.core.axml.ResParserError: UTF-8 String is not null terminated! At offset=211655
```

### System Information

- Androguard Version: master
- Python Version: 3.10
- Operating System: Ubuntu 22.04

Zipped APK file:
[f2ed4cfe79cc4ab87bd4eac06b56044290665a7d64e7f5fd1bc41d8200b7832d.zip](https://github.com/androguard/androguard/files/11840568/f2ed4cfe79cc4ab87bd4eac06b56044290665a7d64e7f5fd1bc41d8200b7832d.zip)

It's open-source file manager from Github: https://github.com/TeamAmaze/AmazeFileManager/releases/tag/v3.8.4

**Comment by erev0s** [comment]
@guri87-byte this should be fixed by https://github.com/androguard/androguard/pull/960
Please feel free to reopen if it persists
