### ISSUE TITLE
AssertionError: "dot" with args ['-Tpng', 'C:\\Users\\walea\\AppData\\Local\\Temp\\tmpx9yppf7q'] returned code: 1

### ISSUE THREAD

**Issue by marshalwahlexyz001** [androguard/androguard#994]
### Describe what you wanted to do
I want to decompile a class in an apk to get the CFG and java source code.

- is this error specific to a single file?

Also when I remove -f png option from the command it also throws a 
**UnicodeEncodeError: 'charmap' codec can't encode characters in position 783-786: character maps to <undefined>**

 It happens across different apk also, because I have about a hundred apk to decompile.

- if possible give a minimal working example where the error happens

Dump Lcom/nigeria/shell/utils/PhoneUtils; getAppVersion (Landroid/content/Context; Ljava/lang/String;)Ljava/lang/String; ... png ... "dot" with args ['-Tpng', 'C:\\Users\\walea\\AppData\\Local\\Temp\\tmp2nsy7hp8'] returned code: 1
stdout, stderr:
 b''
b'Error: not well-formed (invalid token) in line 64 \r\n... <FONT color="red">&quot;context.packageManager.g\x85ckageName, 0).versionName&quot; ...\r\n'

### Describe what you expected
I expect it to decompile the class dumping the png format of the CFG and bytecodes successfully without error

### Describe what actually happened
it stops, and throws an Assertion error for some methods in the class 

### System Information

- Androguard Version: 4.0.2
- Python Version: 311
- Operating System: Windows using Git Bash

### Further Log Files and Output
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\walea\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\Scripts\androguard.exe\__main__.py", line 7, in <module>
  File "C:\Users\walea\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\walea\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\walea\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\walea\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\walea\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\walea\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\androguard\cli\cli.py", line 300, in decompile
    export_apps_to_format(fname, s, output, limit,
  File "C:\Users\walea\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\androguard\cli\main.py", line 159, in export_apps_to_format
    method2format(filename + "." + form, form, None, buff)
  File "C:\Users\walea\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\androguard\core\bytecode.py", line 467, in method2format
    getattr(g, "write_" + _format.lower())(output)
  File "C:\Users\walea\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pydot\core.py", line 1587, in new_method
    self.write(path, format=f, prog=prog, encoding=encoding)
  File "C:\Users\walea\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pydot\core.py", line 1662, in write
    s = self.create(prog, format, encoding=encoding)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\walea\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pydot\core.py", line 1786, in create
    process.returncode == 0
AssertionError: "dot" with args ['-Tpng', 'C:\\Users\\walea\\AppData\\Local\\Temp\\tmp2nsy7hp8'] returned code: 1
![Screenshot 2024-01-26 183635](https://github.com/androguard/androguard/assets/85107092/4f30d186-cf6d-4424-9009-3688270b3809)

- please report logs, tracebacks and other useful information
- if possible report the files you tried to analyze!

**Comment by erev0s** [comment]
pydot can be really troublesome and this part of the code seems to be kind of the same.

See if using `-f raw` improves the situation and if not please share an example apk as well to test against.
